### ISSUE TITLE
How to train custom real dataset like dynerf style?

### ISSUE THREAD

**Issue by yangqing-yq** [hustvl/4DGaussians#101]
Dear author,

Great works!
I found many people has issue on training custom dataset with multiple fixed views , just like dynerf style.
Will you provide a concrete instruction on this task?

thanks,
yq

**Comment by jsxzs** [comment]
Hi, you can refer to the issue #98 . It may help you.

**Comment by yangqing-yq** [comment]
it worked! Thanks!
