### ISSUE TITLE
error when run python train.py in dynerf dataset case "cook_spinach"

### ISSUE THREAD

**Issue by yangqing-yq** [hustvl/4DGaussians#102]
(Gaussians4D) yons@yons-MS-7E06:/dc2/4DGaussians$ no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam03/images, extract images from video. [17/03 13:11:19]
no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam04/images, extract images from video. [17/03 13:12:33]
no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam05/images, extract images from video. [17/03 13:13:46]
no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam06/images, extract images from video. [17/03 13:15:00]
no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam07/images, extract images from video. [17/03 13:16:15]
no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam08/images, extract images from video. [17/03 13:17:31]
no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam09/images, extract images from video. [17/03 13:18:49]
no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam10/images, extract images from video. [17/03 13:20:03]
no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam11/images, extract images from video. [17/03 13:21:21]
no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam12/images, extract images from video. [17/03 13:22:38]
no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam13/images, extract images from video. [17/03 13:23:55]
no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam14/images, extract images from video. [17/03 13:25:08]
no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam15/images, extract images from video. [17/03 13:26:19]
no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam16/images, extract images from video. [17/03 13:27:34]
no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam17/images, extract images from video. [17/03 13:28:49]
no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam18/images, extract images from video. [17/03 13:30:04]
no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam19/images, extract images from video. [17/03 13:31:19]
no images saved in /dc2/4DGaussians/data/dynerf/cook_spinach/cam20/images, extract images from video. [17/03 13:32:34]
meta data loaded, total image:6000 [17/03 13:33:47]
Traceback (most recent call last):
  File "train.py", line 429, in <module>
    training(lp.extract(args), hp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.expname)
  File "train.py", line 303, in training
    scene = Scene(dataset, gaussians, load_coarse=None)
  File "/dc2/4DGaussians/scene/__init__.py", line 53, in __init__
    scene_info = sceneLoadTypeCallbacks["dynerf"](args.source_path, args.white_background, args.eval)
  File "/dc2/4DGaussians/scene/dataset_readers.py", line 463, in readdynerfInfo
    eval_index=0,
  File "/dc2/4DGaussians/scene/neural_3D_dataset_NDC.py", line 254, in __init__
    self.load_meta()
  File "/dc2/4DGaussians/scene/neural_3D_dataset_NDC.py", line 268, in load_meta
    print(" poses_arr.shape[0]:", poses_arr.shape[0])
AssertionError

**Comment by guanjunwu** [comment]
Hi, my friend submit a new [PR](https://github.com/hustvl/4DGaussians/pulls), could we discuss the problem in here?

**Comment by jsxzs** [comment]
@yangqing-yq Hi, you can look at the new [PR](https://github.com/hustvl/4DGaussians/pull/103), which has solved this problem.
In file "4DGaussians/scene/neural_3D_dataset_NDC.py", line 265, you can modify codes like:
```python
videos = glob.glob(os.path.join(self.root_dir, "cam*.mp4"))
```

**Comment by yangqing-yq** [comment]
it worked! Thanks!
