### ISSUE TITLE
Build my own dnerf-like training data

### ISSUE THREAD

**Issue by baoblei** [hustvl/4DGaussians#106]
Hello，is it possible to build my own dnerf-like training data for dynamic scenes captured by a single camera?

**Comment by guanjunwu** [comment]
Hi,
Of course you can! You can check my [HDR-HexPlane dataset](https://github.com/hustvl/HDR-HexPlane). (Though the usage is totally different. But you can rewriter the generation scripts) or [Particle NeRF dataset](https://github.com/jc211/ParticleNeRF).
