### ISSUE TITLE
Problem about hypernerf2colmap.py

### ISSUE THREAD

**Issue by cdfan0627** [hustvl/4DGaussians#108]
Hellow

Thank you very much for your code, I would like to ask the following questions.

<img width="268" alt="image" src="https://github.com/hustvl/4DGaussians/assets/144821204/23946370-50e5-4de5-ae9a-4122ac5e840b">

May I ask why the following problem occurs as long as I change 2x to 1x in hypernerf2colmap.py?
<img width="691" alt="image" src="https://github.com/hustvl/4DGaussians/assets/144821204/95f27c28-b358-4ff3-b089-012010de204c">

**Comment by guanjunwu** [comment]
hi, because the dataset only has "2x" folder.

**Comment by cdfan0627** [comment]
Hello, sorry, I am using hypernerf's misc_espresso, which contains dataset has "1x" folder

**Comment by guanjunwu** [comment]
Hi, if you want to use "1x", I think you can change the` imagesize`,` camera parameters` of `line 71`.
Maybe that will work?

**Comment by cdfan0627** [comment]
不好意思，但是他的image size是讀camera json檔案的image size，那個camera json檔案的image size，就是1x的image size

**Comment by guanjunwu** [comment]
我这里是2x的，我觉得你只要把71行的那个
`    print(idx,"SIMPLE_PINHOLE",image_size[0]/2,image_size[1]/2,cam['focal_length']/2,cam['principal_point'][0]/2,cam['principal_point'][1]/2,file=object_cameras_file)`
改成
`    print(idx,"SIMPLE_PINHOLE",image_size[0],image_size[1],cam['focal_length'],cam['principal_point'][0],cam['principal_point'][1],file=object_cameras_file)`，是不是就行了

**Comment by cdfan0627** [comment]
成功了 非常感謝您的幫忙!
