### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/dynerf/basketball-20/poses_bounds.npy'

### ISSUE THREAD

**Issue by yangqing-yq** [hustvl/4DGaussians#110]
$ python scripts/preprocess_dynerf.py --datadir data/dynerf/basketball-20
Traceback (most recent call last):
  File "scripts/preprocess_dynerf.py", line 13, in <module>
    scene_bbox_min=[-2.5, -2.0, -1.0], scene_bbox_max=[2.5, 2.0, 1.0], eval_index=0)    
  File "./scene/neural_3D_dataset_NDC.py", line 258, in __init__
    self.load_meta()
  File "./scene/neural_3D_dataset_NDC.py", line 266, in load_meta
    poses_arr = np.load(os.path.join(self.root_dir, "poses_bounds.npy"))
  File "/home/yons/anaconda3/envs/Gaussians4D/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/dynerf/basketball-20/poses_bounds.npy'

**Comment by guanjunwu** [comment]
Hi，what is basketball dataset?

**Comment by yangqing-yq** [comment]
> Hi，what is basketball dataset?

that is my self-made synthetic dataset. The camera setting is similar to dynerf dataset, like coffee_martini.

**Comment by yangqing-yq** [comment]
I have made poses_bounds.npy with llff repo. I think you can change your instruction for custom dataset. Since the original dataset is without poses_bounds.npy but only mp4 files. But your preprocessing script requires the npy file without producing it.

**Comment by guanjunwu** [comment]
E, what's your current folder format now, could you show me?

**Comment by yangqing-yq** [comment]
-basketball-20
--cam00.mp4
--cam01.mp4
--cam02.mp4
...
--cam20.mp4

**Comment by Harryhaozhu** [comment]
> -篮球-20 --cam00.mp4 --cam01.mp4 --cam02.mp4 ... --cam20.mp4

您好，您的.npy是如何生成的，我使用llff的imgs2poses.py生成的，但我觉得生成的不对，因为这种生成的.npy训练效果相当差，我是用dynerf数据集的.npy和用llff生成的.npy做过对比，差距很大，请问您如何生成的您的.npy
