### ISSUE TITLE
handling custom camera intrinsics

### ISSUE THREAD

**Issue by hdacnw** [hustvl/4DGaussians#112]
Hi there, thanks for the great work! 

I was wondering if it's possible to handle different camera intrinsics per frame e.g. different fx, cx? Specifically, can I modify `getProjectionMatrix`  in `graphics_utils.py` by supplying custom P matrix to achieve this?

Thanks again.

**Comment by Tonychen050400** [comment]
Hi, I face the similar question, do you solve this problem?
