### ISSUE TITLE
HyperNeRF Point Cloud Issue

### ISSUE THREAD

**Issue by jeff999955** [hustvl/4DGaussians#116]
Hi, 

I am using your script to generate the point cloud with COLMAP for HyperNeRF scenes, and I found some misalignment (plz see the image below) when I project all points onto the image. Could you please host the point cloud for HyperNeRF somewhere? Thank you.

![image](https://github.com/hustvl/4DGaussians/assets/31263714/7664b91f-38b5-4424-b636-d860578307ee)

**Comment by guanjunwu** [comment]
Hi,
please refer [this  link](https://drive.google.com/drive/folders/1y98-e18HEcBQqzSGdABf1P_1y4FNcvq7?usp=drive_link)

**Comment by jeff999955** [comment]
Thank you!
