### ISSUE TITLE
HyperNeRF colmap.sh issue

### ISSUE THREAD

**Issue by Subinn-Jeon** [hustvl/4DGaussians#117]
Hi. Thank you for sharing your great work!

I'm a beginner of this field, and I got a problem relating to colmap of HyperNeRF data (broom, chicken and so on)
I downloaded data from HyperNeRF, and ran colmap.sh as follows.

bash colmap.sh data/hypernerf/vrig/vrig-chicken/ hypernerf
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 328/328 [00:00<00:00, 31469.75it/s]
164
colmap.sh: line 15: colmap: command not found
ERROR: database path dosen't exist -- please check database.db.
colmap.sh: line 17: colmap: command not found
colmap.sh: line 20: colmap: command not found
colmap.sh: line 23: colmap: command not found
colmap.sh: line 24: colmap: command not found
colmap.sh: line 25: colmap: command not found

I couldn't find database.db file from the original downloaded files, and I think it causes the problem.
How can I fix this error?

Hope hear from you soon! Thank you!

**Comment by guanjunwu** [comment]
it seems like your computer didn't install colmap, you should install it at first :)
