### ISSUE TITLE
Pre-processing Neu3D dataset

### ISSUE THREAD

**Issue by HyoKong** [hustvl/4DGaussians#122]
Hi, thank you so much for your wonderful work!

May I ask how to pre-process the Neu3D dataset? After organizing the dynerf dataset as follows, how to obtain the ply and camera-related files based on the extracted frames with different camera ids?

```
├── data
│   | dnerf 
│     ├── mutant
│     ├── standup 
│     ├── ...
│   | hypernerf
│     ├── interp
│     ├── misc
│     ├── virg
│   | dynerf
│     ├── cook_spinach
│       ├── cam00
│           ├── images
│               ├── 0000.png
│               ├── 0001.png
│               ├── 0002.png
│               ├── ...
│       ├── cam01
│           ├── images
│               ├── 0000.png
│               ├── 0001.png
│               ├── ...
│     ├── cut_roasted_beef
|     ├── ...
```

Thanks in advance!

**Comment by guanjunwu** [comment]
Hi, the detailed process is illstruated in the readme.md, please check the file :)

**Comment by HyoKong** [comment]
Hi, thanks for your fast reply. Is the Neu3D dataset one of the multi-view datasets? Is there any difference between multipleview_dataset and Neural3D_NDC_Dataset?

**Comment by HyoKong** [comment]
I checked videos in the Neu3D dataset and it seems that the videos are captured using cameras with various poses simultaneously.

**Comment by guanjunwu** [comment]
yes, neu3D dataset equals to Neural3D_NDC_Dataset.
multipleview_dataset is similar to neu3D dataset but no GT poses are provided. So we add a precomputed poses process.

**Comment by HyoKong** [comment]
Well noted. thank you so much!

**Comment by VLadImirluren** [comment]
@HyoKong Could you please share the point cloud obtained in the second stage (or after the whole preprocessing)? My linux failed to run colmap.sh although after installing the dependencies. Thanks..
(My Email: dengkennn@gmail.com, or directly upload on github.... Really need your help...)

**Comment by Harryhaozhu** [comment]
> [@HyoKong](https://github.com/HyoKong)能否分享一下第二阶段（或整个预处理过程之后）得到的点云文件？我的Linux系统虽然安装了依赖项，但仍然无法运行colmap.sh脚本。谢谢！ （我的邮箱是[dengkennn@gmail.com](mailto:dengkennn@gmail.com)，或者可以直接上传到GitHub……真的非常需要您的帮助……）

您好，您使用多视角进行实验了吗，效果如何，我的效果非常差，感觉是相机位姿计算的就有错，但是我完全按照每一步进行的，不知如何调试了
