### ISSUE TITLE
AssertionError: Could not recognize scene type!

### ISSUE THREAD

**Issue by carolinaicardi1** [hustvl/4DGaussians#138]
Hi,  I have already succesfully trained a hypernerf dataset and everything works, now I'm trying to use my own dataset but I have some problems. The processing seems to be working, but the training immediately stops. The error is "AssertionError: Could not recognize scene type!". Here are the screens of the processing results:
**![processingError](https://github.com/hustvl/4DGaussians/assets/115872783/9570b202-f685-478a-94d4-08b99fba9eb1)**
![cartelleOutput](https://github.com/hustvl/4DGaussians/assets/115872783/1fcc61bf-3936-4da2-b549-fa8014823228)

This is the training error. 
![condaerror](https://github.com/hustvl/4DGaussians/assets/115872783/4285f341-1981-4885-9caf-0b1a35e58910)

**Comment by guanjunwu** [comment]
![image](https://github.com/hustvl/4DGaussians/assets/87054407/075b2b75-1132-4d22-9ff8-b5a781208c78)
Can you check your colmap dir's format, like this?
(create dir named '0')
and copy your `images` folder into `colmap` folder.

**Comment by carolinaicardi1** [comment]
Hi, thanks for your reply. I've already copied my images in the colmap folder. The points3D.ply file is missing, but I was looking at the hypernerf dataset I've proccesed and trained successfully and the file isn't there too. 

![colmap](https://github.com/hustvl/4DGaussians/assets/115872783/501282b3-b23d-4985-b588-a6afb2a29a32)

![0](https://github.com/hustvl/4DGaussians/assets/115872783/9f4d1c97-a38d-46aa-80e2-ba5c977ada69)

**Comment by carolinaicardi1** [comment]
I solved the issue, thank you for your help.
