### ISSUE TITLE
Error when Training (in gaussian_renderer/__init__.py, ValueError: not enough values to unpack) 

### ISSUE THREAD

**Issue by bootcap** [hustvl/4DGaussians#145]
I training 4DGaussians with dynerf cut_roasted_beef dataset.
Here is what I got when I running the final step of training " python train.py -s data/dynerf/cut_roasted_beef --port 6017 --expname "dynerf/cut_roasted_beef" --configs arguments/dyn erf/cut_roasted_beef.py":

Optimizing
Output folder: ./output/dynerf/cut_roasted_beef [21/06 01:44:43]
feature_dim: 32 [21/06 01:44:43]
meta data loaded, total image:5700 [21/06 01:44:44]
meta data loaded, total image:300 [21/06 01:44:44]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5700/5700 [00:00<00:00, 250702.93it/s]300it [00:00, 51390.29it/s]
origin points, 37338 [21/06 01:44:45]
after points, 37338 [21/06 01:44:45]
Loading Training Cameras [21/06 01:44:45]
Loading Test Cameras [21/06 01:44:45]
Loading Video Cameras [21/06 01:44:45]
Deformation Net Set aabb [22.05381012 32.12039948 50.11937332] [-25.69946861 -15.22493935   5.43103194] [21/06 01:44:45]
Voxel Plane: set aabb= Parameter containing:
tensor([[ 22.0538,  32.1204,  50.1194],
        [-25.6995, -15.2249,   5.4310]]) [21/06 01:44:45]
Number of points at initialisation :  37338 [21/06 01:44:46]
Training progress:   0%|                                                                                                                                               | 0/3000 [00:00<?, ?it/s]data loading done [21/06 01:44:46]
Traceback (most recent call last):
  File "train.py", line 434, in <module>
    training(lp.extract(args), hp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.expname)
  File "train.py", line 310, in training
    scene_reconstruction(dataset, opt, hyper, pipe, testing_iterations, saving_iterations,
  File "train.py", line 186, in scene_reconstruction
    render_pkg = render(viewpoint_cam, gaussians, pipe, background, stage=stage,cam_type=scene.dataset_type)
  File "/home/cap/GS/4DGaussians/gaussian_renderer/__init__.py", line 120, in render
    rendered_image, radii, depth = rasterizer(
ValueError: not enough values to unpack (expected 3, got 2)
Training progress:   0%|

Could anyone help me fix this problem?

**Comment by guanjunwu** [comment]
Hi， which gaussian rasterization code do you use?
just use codelib referenced in readme files

**Comment by bootcap** [comment]
Thanks for your help!! I really appreciate it!

**Comment by GunGirl-cp** [comment]
I have the same problem as you, could you tell me how you solved it?

**Comment by chenj02** [comment]
I have the same problem as you, could you tell me how you solved it?

**Comment by bootcap** [comment]
just update the rasterization. do not use original 3dgs env.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bootcap** [comment]
just update the rasterization code. do not use original 3dgs env.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
