### ISSUE TITLE
Parameter Optimization

### ISSUE THREAD

**Issue by Spawnfile** [hustvl/4DGaussians#149]
Hi all,

Is there any doc to follow-up purpose of all parameters inside the `arguments/.../default.py` ? Besides, any suggestion to optimize render quality on parameter section ? 

Cheers

**Comment by guanjunwu** [comment]
Hi, [there](https://github.com/hustvl/4DGaussians/blob/master/arguments/__init__.py)
if you have any question, please contact me.

**Comment by Spawnfile** [comment]
That was quick, thank you. Is any suggestion parameters, probably optimization parameters, to smooth the object edges with white background ?

**Comment by guanjunwu** [comment]
It's hard for 3D/4D Gaussian splatting. Because Gaussians only focus on novel view synthesis instead of reconstruction(mesh).
