### ISSUE TITLE
hust的大神，要不要来个: Dream Dymamic Gauss?

### ISSUE THREAD

**Issue by yuedajiong** [hustvl/4DGaussians#15]
感觉现在没数据。

shape:    
zero123(xl)只能弱弱的带点shape的priori过来。多view都还差很远。

dynamic:  
还没有一个更大的数据集和相关的表示:   各种object，各种pose/action/motion的数据集。   
类似frame的表示感觉不行，要么有个chatgpt至少百倍大小的模型来隐式， 要么就是template + drive-vector显示的驱动。

**Comment by guanjunwu** [comment]
感谢你的参与与交流！

关于4DGS Dreamer，现在唯一一篇论文似乎是MetaAI的text 2 4d，还没开源。实际上来说实现这个问题难度挺大的，中间有很多坑，目前text 2 video其实效果也不是很好（当然抖音上的control net已经不错了，不过用起来很麻烦）我们之后会继续关注这个问题。

**Comment by yuedajiong** [comment]
te表示的约束信息太少了，自由文本输入的化，操作也不精细：  一个男人用食指摸了摸睫毛。  就很难搞出来。还有interaction。

text感觉只能软性的对应到某些动作网络上输出一个laten然后+/cat到后面的网络。

动作描述text  < 火柴棍动作描述  <  参考动作图片/keypoints or laten repre  <  参考运动视频  <  control-net UI交互  < ...

**Comment by guanjunwu** [comment]
的确是的，但是能通过尽量简单的prompt来得到尽可能炫酷&有用的结果也是大家所追求的，毕竟大语言模型都那么给力（虽然对应也催生出了prompt engineer）。
模拟自然特别是流体&粒子的运动特别难，有好多大佬都在研究这个，背后应该是要加很多很多物理约束的。相信他们很快就会给出一个很好的solution :)
