### ISSUE TITLE
About DSSIM Loss and opacity reset

### ISSUE THREAD

**Issue by AAAmazin** [hustvl/4DGaussians#152]
Hello, thanks to your contribution. I have some questions about your code,  Why don't you use DSSIM loss, and reset opacity .  Does the deformation field correctly model rigid motion, rather than a state fitted by multiple deformations? Looking forward to your reply.Thanks.

**Comment by guanjunwu** [comment]
Hi,
DSSIM may let training speed become slower. If you add this, the results will be better.
Currently, deformation field cannot model rigid motion accurately there are some small errors :)
maybe using tracking priors or flow as supervision will be better.
Best wishes!

**Comment by AAAmazin** [comment]
Thank you so much for your prompt response. Your answers have been incredibly helpful!
