### ISSUE TITLE
Exporting Camera Path from Nerfstudio for Using Here

### ISSUE THREAD

**Issue by Spawnfile** [hustvl/4DGaussians#157]
Hello everyone,

I'm trying to change camera paths on render section. **Nerfstudio** helps exporting camera path from GUI they provide on 3DGS (.PLY) files. Therefore, there are two questions I wonder,

1. How can I export or implement these exported paths as function that replaces `get_spiral` function on render.py ?
2. Is it possible to render 4GDS outputs which trained with this repo, on **nerfstudio** with custom camera paths ? 

Cheers

**Comment by Dnotitiajhcha** [comment]
I have same questions, too.

**Comment by guanjunwu** [comment]
I think just writing a script for pose transformation can help you solve the problem.
3DGS/4DGS uses colmap poses and there is litter different from Nerfstudio's camera poses.
