### ISSUE TITLE
Training failure due to the scale difference between the offset and the canonical space gs.

### ISSUE THREAD

**Issue by Time-Lord12th** [hustvl/4DGaussians#166]
Hello，
Thanks for your great work. Have you ever encountered training failure due to the scale difference between the offset and the canonical space gs? 
For example, the position range of the canonical space gs is [-0.2, 0.2], while the offset range output by the deformation model is [-1, 1]. So most of the gs will be deformed out of the camera's field of view, causing a large difference between the rendered image and the ground truth, making it impossible for the model to optimize properly.
Do you have any opinion on this issue?

**Comment by guanjunwu** [comment]
yes of course, you can just change the initialization of the deformation field in [L221](https://github.com/hustvl/4DGaussians/blob/605a0921c5cbcad3314a1efc9dcc093c225cc1b1/scene/deformation.py#L221) and L223.

**Comment by Time-Lord12th** [comment]
thanks, but I wonder why L221 and L223 are the same. L223 should initialize m.bias?
![image](https://github.com/user-attachments/assets/35e96146-1de9-49b7-a204-d416d4bda1bd)

**Comment by guanjunwu** [comment]
Yes, you can set different initialize level, but I think you can only modify L221.

**Comment by Time-Lord12th** [comment]
thanks for your advice！
