### ISSUE TITLE
运行 (4dgs2) zc107552403943@gpuadmin-G560-V5:~/4DGaussians$ bash colmap.sh data/dynerf/cook_spinach llff出错

### ISSUE THREAD

**Issue by CBDXS1** [hustvl/4DGaussians#169]
colmap.sh: line 15: colmap: command not found
ERROR: database path dosen't exist -- please check database.db.
colmap.sh: line 17: colmap: command not found
colmap.sh: line 20: colmap: command not found
colmap.sh: line 23: colmap: command not found
colmap.sh: line 24: colmap: command not found
colmap.sh: line 25: colmap: command not found

**Comment by lulinliu** [comment]
I think you need to install colmap first.
