### ISSUE TITLE
针对单相机的提问

### ISSUE THREAD

**Issue by shenqianxiang** [hustvl/4DGaussians#177]
我有一个疑问，如果是多相机的情况下，每个时间步都可以产生gt与预测进行对比，但是单相机呢，初始场景和gt是怎么产生的？

**Comment by guanjunwu** [comment]
在实验条件下，gt有两种：
1. 用若干个相机同时拍摄，一个相机训练，其他的相机用来测试
2. 一个相机拍摄，中间取几帧做test

**Comment by shenqianxiang** [comment]
原谅我只是一个小白，我的意思是，单摄像机移动拍摄动态场景，如何构建初始的点云？  据我所知，多摄像机可以通过sfm构建每个时间步的点云

**Comment by guanjunwu** [comment]
重新理一下：
1. 单目相机：n个时刻n张照片，我们直接把这n张照片送给sfm，sfm会进行重建并匹配点云。由于sfm是基于静态的假设，所以动态的部分通常不会有点云匹配出来，而静态的部分会有点云初始化。
2. 多目相机：4DGS中会用t=0时刻的照片送入sfm初始化点云。
