### ISSUE TITLE
the meaning of Δx, Δy and Δz

### ISSUE THREAD

**Issue by zdrac** [hustvl/4DGaussians#187]
hi😊, I want to confirm the meaning of Δx, Δy and Δz. Do they represent the change from the initial position at each timestamp? And if you subtract two adjacent terms, you get the change in position of adjacent frames, right?

**Comment by guanjunwu** [comment]
the delta x,y,z means the deformation between  **canonical 3D Gaussians** and **world 3D Gaussians**
if you want to get deformation between two adjacent frames, you should:
1. compute the 3D Gaussian's position x1 at timestamp t1
2. compute the 3D Gaussian's position x2 at timestamp t2
3. return x2-x1
