### ISSUE TITLE
DeformNetwork.timenet is unused

### ISSUE THREAD

**Issue by ringohoffman** [hustvl/4DGaussians#20]
It is never applied in `DeformNetwork.forward`. Is this intentional? https://github.com/search?q=repo%3Ahustvl%2F4DGaussians%20self.timenet&type=code

**Comment by guanjunwu** [comment]
Indeed, we have tried using timenet for ablation study but it seems not work very well. So we didnt use it.
Thank you for your comment, we will delete it in the next version.
