### ISSUE TITLE
Using It for Scene Reconstruction

### ISSUE THREAD

**Issue by tobottyx** [hustvl/4DGaussians#207]
Hello, thank you for your excellent work. I am not a researcher in this field; I simply want to use it to reconstruct a desktop scene by mutiview capturing RGB-D information through a camera and then performing the reconstruction. Could you give me some guidance? Do I need to retrain the model myself?

**Comment by guanjunwu** [comment]
yes, you should train the model by yourself.
You can follow the multipleview training guidance to setup your dataset. The number of training camera should be more than 5 and remain fixed(if not, colmap will fail) Or you can prepare the dataset like Nerfstudio's dataformat.

**Comment by tobottyx** [comment]
好的，非常感谢！
