### ISSUE TITLE
多视角数据预处理

### ISSUE THREAD

**Issue by MikeAiJF** [hustvl/4DGaussians#210]
![image](https://github.com/user-attachments/assets/0061c1f5-1a0e-49d4-9367-7f7f4fc6eca6)

**Comment by JingjinNong** [comment]
> ![image](https://private-user-images.githubusercontent.com/146935101/388819487-0061c1f5-1a0e-49d4-9367-7f7f4fc6eca6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTY5MTQsIm5iZiI6MTczMjUxNjYxNCwicGF0aCI6Ii8xNDY5MzUxMDEvMzg4ODE5NDg3LTAwNjFjMWY1LTFhMGUtNDlkNC05MzY3LTdmN2Y0ZmM2ZWNhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwNjM2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWYyNjA5NjA1NDBhYWU1MTVlYTI1N2JjZTk4NTVlYzZkMzY2ZjNiOTYzZDRmNDk0MmMzOTBiYjhhMTRkMDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9fOzWnW855B4hJ6Xvz3cC1WLSOlWu1emOVk-MBtKUgo)

I've met the same problem and I'm sure that I've followed every step as author writes

**Comment by JingjinNong** [comment]
我目前解决了这个问题，成功跑通了。
该报错来自于pose_utils.py的第63行，原因是参数cam和ind分别来自于colmap输出的images.bin和point3d.bin文件，如果输入给colmap的数据质量不足，会造成这两个参数维度不一致。

解决方法是保证输入给colmap的每个相机都参与训练。
也可以通过查看colmap_temp/dense/images（需要把multipleviewprogress.sh的最后两行注释掉），查看该文件夹下的图片来自于哪一个相机，在mutipleview里只保留这些相机的cam文件夹即可。

**Comment by MikeAiJF** [comment]
> 我目前解决了这个问题，成功跑通了。 该报错来自于pose_utils.py的第63行，原因是参数cam和ind分别来自于colmap输出的images.bin和point3d.bin文件，如果输入给colmap的数据质量不足，会造成这两个参数相互矛盾。
> 
> 解决方法是保证输入给colmap的每个相机都参与训练。 也可以通过查看colmap_temp/dense/images（需要把multipleviewprogress.sh的最后两行注释掉），查看该文件夹下的图片来自于哪一个相机，在multipleview里只保留这些相机的cam文件夹即可。
好的，感谢！

**Comment by MikeAiJF** [comment]
> 我目前解决了这个问题，成功跑通了。 该报错来自于pose_utils.py的第63行，原因是参数cam和ind分别来自于colmap输出的images.bin和point3d.bin文件，如果输入给colmap的数据质量不足，会造成这两个参数相互矛盾。
> 
> 解决方法是保证输入给colmap的每个相机都参与训练。 也可以通过查看colmap_temp/dense/images（需要把multipleviewprogress.sh的最后两行注释掉），查看该文件夹下的图片来自于哪一个相机，在multipleview里只保留这些相机的cam文件夹即可。
![image](https://github.com/user-attachments/assets/c443adc3-ee6d-4fef-8de0-eefccf2c0a3c)
还是这个错误，需要5个相机位姿，但是dense下面只有2个相机位姿。63行代码需要更改吗

**Comment by guanjunwu** [comment]
你好，我这个脚本的设计就是基于多目数据集的，摄像头最好多于5个（不然colmap跑不出来）如果少于5个那就回到了稀疏重建的范畴了，建议用一些其他的方法，比如dust3r来算pose

**Comment by ccxi1008** [comment]
> 你好，我这个脚本的设计就是基于多目数据集的，摄像头最好多于5个（不然colmap跑不出来）如果少于5个那就回到了稀疏重建的范畴了，建议用一些其他的方法，比如dust3r来算pose

你好 我的相机有21个 但是也会出现同样的结果

![Image](https://github.com/user-attachments/assets/52d2c79b-1ce1-48cc-bf36-d240f622e908)

**Comment by Harryhaozhu** [comment]
> > 你好，我这个脚本的设计是基于多目数据集的，网络头最好多于5个（不然colmap跑不出来）如果少5个回到那就了稀疏重建的中央了，建议用一些其他的计算方法，比如dust3r来pose
> 
> 你好我的相机有 21 个但出现同样的结果
> 
> ![Image](https://github.com/user-attachments/assets/52d2c79b-1ce1-48cc-bf36-d240f622e908)

您好，解决了吗，我也相同的问题
