### ISSUE TITLE
What is the coordinate of the pose_spherical func?

### ISSUE THREAD

**Issue by xiao10ma** [hustvl/4DGaussians#216]
Thank you for your great work.

I'm wondering what is the coordinate of the intermediate poses generated by the `pose_spherical` [here](https://github.com/hustvl/4DGaussians/blob/master/scene/dataset_readers.py#L218). 

I can understand that the results of the `pose_spherical` is Blender coordinate, since:
```
        matrix = np.linalg.inv(np.array(poses))
        R = -np.transpose(matrix[:3,:3])
        R[:,0] = -R[:,0]
        T = -matrix[:3, 3]
```

but what is the coordinate of the c2w:
```
        c2w = trans_t(radius)
        c2w = rot_phi(phi/180.*np.pi) @ c2w
        c2w = rot_theta(theta/180.*np.pi) @ c2w
```

Since Blender camera coordinate is R(ight)U(p)B(ackward), and you do 
`c2w = torch.Tensor(np.array([[-1,0,0,0],[0,0,1,0],[0,1,0,0],[0,0,0,1]])) @ c2w`, the intermediate coordinate is LBU??? (R -> L, y and z exchange) But what's that???

**Comment by xiao10ma** [comment]
By the way, are the parameters `theta` and `phi` in the pose_spherical function reversed?

**Comment by guanjunwu** [comment]
Hi, please refer to [BlenderNeRF](https://github.com/maximeraafat/BlenderNeRF)
