### ISSUE TITLE
Severe artifacts in N3dv coffee scene

### ISSUE THREAD

**Issue by Friedrich-M** [hustvl/4DGaussians#22]
When I run the code using the command as follows:

```bash
export CUDA_VISIBLE_DEVICES=2
expname='coffee_martini'
port=6080
python train.py -s data/dynerf/${expname} --port ${port} --expname "dynerf/${expname}" --configs arguments/dynerf/default.py  &
wait
python render.py --model_path output/dynerf/${expname} --configs arguments/dynerf/default.py --skip_train --skip_test &
wait
python metrics.py --model_path output/dynerf/${expname}/  &
wait
echo "Done"
```

I found the rendered video has a lot of artifacts and the quality seems much lower than it is in the paper.

https://drive.google.com/file/d/14QJRuNAjHiPiHqyHM1aCiOfEXYWb2vP-/view?usp=sharing

**Comment by guanjunwu** [comment]
Indeed, in this version of our code, 4D-GS cannot perform very well in the scenes with out-door backgrounds(due to the lack of point clouds initialization). We are working hard to improve the rendering quality :)

**Comment by Friedrich-M** [comment]
Thank you for your reply. I was wondering if there are any scenes that perform relatively well on n3dv?

**Comment by guanjunwu** [comment]
https://github.com/masked-spacetime-hashing/msth

**Comment by Friedrich-M** [comment]
I've run their code through this open-source repository, but I found their current version of the code to be messy and didn't test very well.

![img_30000_01a2e473b522f76b6ab7](https://github.com/hustvl/4DGaussians/assets/85838942/0874facc-8f2c-48b6-bc07-71ab92bbb03e)

**Comment by guanjunwu** [comment]
It seems that [HexPlane](https://github.com/Caoang327/HexPlane) and [KPlanes](https://github.com/Giodiro/kplanes_nerfstudio) may help you :)
btw, you can check the results comparasion mentioned in papers.
