### ISSUE TITLE
How to output the per-frame point cloud or mesh

### ISSUE THREAD

**Issue by JunhuaLiu0** [hustvl/4DGaussians#24]
Thanks for the great work.

I now want to export the contents of each frame for editing. The output of Siggraph 2023 3D Gaussian is a.ply file, and I can easily get the corresponding point cloud and mesh. For 4D Gaussian, I want to know how to get the deformable position of 3D Gaussian in each frame so that I can output the per-frame point cloud or mesh.

Any possible advice or practice would be very helpful to me. Thank you sincerely.

**Comment by JunhuaLiu0** [comment]
Sorry for disturbing you again. That's not what I'm looking for. 

What you provide is to store the static point cloud on different training iterations. Since this is a dynamic Gaussian, what I want is the point cloud of each frame when the dynamic Gaussian is played after training.

**Comment by JunhuaLiu0** [comment]
I have modified a version myself and it has worked now. Thank you for your answer : )

**Comment by henrypearce4D** [comment]
@JunhuaLiu0 could you share your modification?

**Comment by imjxy** [comment]
@JunhuaLiu0 could you share your modification? Or can you provide some hints?
Thank you

**Comment by imjxy** [comment]
> I have modified a version myself and it has worked now. Thank you for your answer : )我自己修改了一个版本，现在已经可以运行了。谢谢您的回答 ： ）

@junhua-l could you share your modification? Or can you provide some hints?
Thank you

**Comment by Guoxni** [comment]
> 我自己修改了一个版本，它现在已经工作了。谢谢你的回答 ：）

Hello, could you please share your implementation method?
