### ISSUE TITLE
Rendering Quality of hypernerf split-cookie scene

### ISSUE THREAD

**Issue by whwjdqls** [hustvl/4DGaussians#36]
hi, thanks for this great research paper. 
While I was playing with the code, I found multiple cases where the results did not match the results shown in the paper and the project page. 
As the project page shows a good result on hypernerf cookie-split dataset, these are the rendering quality after training with the script files in the repo. 

![image](https://github.com/hustvl/4DGaussians/assets/73946308/c93bb813-7a53-4215-8d79-2fee643da13c)

![image](https://github.com/hustvl/4DGaussians/assets/73946308/b35fa932-c975-4aa8-b7d8-69985bd89df8)

I was wondering if there are any more details on this specific scene as the results are not reproducible.

**Comment by guanjunwu** [comment]
you can generate point clouds by colmap using training images.
To be honest. I also found that 4DGS is a direct and naive approach to solving dynamic scenes. It only works very well in synthesis datasets and has no explicit advantage compared to other dynamic NeRFs except rendering speed (maybe 4DGS have but I haven't achieved that). And in my opinion, 4DGS can also perform tracking and editing like [dynamic3dgs](https://github.com/JonathonLuiten/Dynamic3DGaussians)

I do think more prior should be adopted (such as optical flow) in monocular scenes and using methods like (4K4D)[https://github.com/zju3dv/4K4D], (Im4D)[https://github.com/zju3dv/im4d] in multi-cam setup can achieve better rendering quality.

**Comment by whwjdqls** [comment]
Thanks for the prompt reply and your opinion. 

Hope you guys keep up the great work! 👍

**Comment by guanjunwu** [comment]
btw, you can set batch_size = 4 and training iteration=14000. It works in my machine.
