### ISSUE TITLE
simple_knn submodule is missing

### ISSUE THREAD

**Issue by Solcany** [hustvl/4DGaussians#39]
simple_knn submodule points to a broken link @ https://github.com/hustvl/4DGaussians/blob/master/submodules/simple-knn

Thus running `git submodule update --init --recursive` leaves the submodules/simple_knn folder empty

**Comment by guanjunwu** [comment]
I reproduced the results just now, but the module can be installed successfully, have you solved it?

**Comment by Huotianci** [comment]
Hello, now, simple_knn submodule is still missing. Can you help me?
Thanks.

**Comment by guanjunwu** [comment]
@Huotianci 
https://github.com/camenduru/simple-knn
here
