### ISSUE TITLE
subprocess-exited-with-error   x python setup.py develop   TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by Sabisisi** [hustvl/4DGaussians#45]
When running pip install -e submodules/depth-diff-gaussian-rasterization , I keep getting an error message that looks like this:

(Gaussians4D) C:\Users\Manu\4DGaussians>pip install -e submodules/depth-diff-gaussian-rasterization
Obtaining file:///C:/Users/Manu/4DGaussians/submodules/depth-diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Installing collected packages: diff-gaussian-rasterization
  Running setup.py develop for diff-gaussian-rasterization
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [60 lines of output]
        running develop
        running egg_info
...

writing manifest file 'diff_gaussian_rasterization.egg-info\SOURCES.txt'
    running build_ext
    No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
    C:\Users\Manu\anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    C:\Users\Manu\anaconda3\envs\Gaussians4D\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    C:\Users\Manu\anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    C:\Users\Manu\anaconda3\envs\Gaussians4D\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
      warnings.warn(f'Error checking compiler version for {compiler}: {error}')
    Traceback (most recent call last):
      File "<string>", line 36, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>

...

 File "C:\Users\Manu\anaconda3\envs\Gaussians4D\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 264, in __init__
            match = self._regex.search(version)
        TypeError: expected string or bytes-like object
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

I tried several things like 
- installing cuda 11.7 instead of 11.8 
- create a CUDA_HOME system variable to the path where cuda is installed
- manually install ninja via > pip install ninja
- checked if my versions of pytorch and cuda are compatible
- run setup.py via cd submodules/depth-diff-gaussian-rasterization
python setup.py develop
- update the setuptools via pip install --upgrade setuptools

and some other things but nothing worked.
Some actions changed the number of lines of output. In the beginning it was 58 lines of output, then 56, then 78, now 60.

I deleted the 4DGaussians folder, started from scratch but nothing changed.
Earlier today, I trained a normal 3D GS and everything worked just fine.

I'm working with
- Win 10
- RTX 4090
- conda 23.7.4
- Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
- torch Version: 1.13.1

Please let me know if there is any way to fix this, I don't know what else I could try!
Thanks to the devs for this amazing project, hope it's possible to fix this issue and start working with it!

**Comment by guanjunwu** [comment]
I think you can install or update `cl`?

**Comment by Sabisisi** [comment]
I did, but it didn't solve the issue. I did via the command: conda install -c anaconda vc ; tried via the VS installer, updated it, and added the path to the system variables (it wasn't there before), but I keep getting the same error message.

**Comment by Sabisisi** [comment]
@guanjunwu What else can we try to fix this? I really want to make this work on my machine and am happy to collaborate with you and/or your colleagues

**Comment by guanjunwu** [comment]
emmmmm
If 3D-GS works, you can modify the origin training code.
Can you delete the forward pass of rendering depth? It seems not difficult

**Comment by Sabisisi** [comment]
I will try and let you know!

**Comment by Sabisisi** [comment]
Sorry for getting back to that so late, I first wanted to try any possible solution before writing again.

I tried your advice and many other possibles fixes without success, until I found a solution that seemed to work:

after
pip install -r requirements.txt

I went with 
pip uninstall torch torchvision
pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 -f https://download.pytorch.org/whl/torch_stable.html

and then continued with
pip install -e submodules/depth-diff-gaussian-rasterization
pip install -e submodules/simple-knn


It seemed that when I tried to manually install other cuda and/or torch versions in the past, it didn't go through completely. That seems strange to me, I always checked afterwards with 'pip3 show torch' and 'nvcc --version', to verify if the installation was successful. It seems that the installation via conda was not entirely possible, others have mentioned something similiar.


After some unsuccessful attempts before, I reinstalled windows. Strangely, I kept getting also error messages when trying to install the normal 3DGS set up then, also a cuda issue. That didn't happen the first time, before reinstalling windows. The computer was clean before, no idea what changed. I couldn't fix it following the solutions of others that experienced similiar problems until I found this here (works for me for 3DGS-install: 
after a non successful entire installation

conda activate gaussian_splatting
conda install -c anaconda vs2019_win-64
conda env update --file environment.yml



For the fixed issue with 4DGS, I couldn't verify if everything works for now, as I can not view the trained model/ results. At least the installation seemed to be successful. I will try to make one of the viewing approaches mentioned on the other issue page work and keep you posted. Won't have the computer until the beginning of next year.

It would be nice if you could add a viewer/ link to a method to view the trained models to your repo or docu!
Thx again for your work!

**Comment by chy2013920202** [comment]
Hello, you can try installing torch==1.13.1+cu117
