### ISSUE TITLE
How to Create custom dataSets for training?

### ISSUE THREAD

**Issue by chongxian** [hustvl/4DGaussians#46]
Hello, I have gone through the entire issues and I have a lot of doubts about how to build my own dataset. I have successfully compiled NerfStudio, but it can only generate data in colmap format and cannot convert it to Blender format. Additionally, the Readme does not provide instructions on how to train a generic dataset. I would greatly appreciate it if you could provide me with a solution.

**Comment by leo-frank** [comment]
In the function [readColmapCameras](https://github.com/hustvl/4DGaussians/blob/a2de1841756f49f7bf8d4b2f6fcad0ee5a8324ae/scene/dataset_readers.py#L116), i find that the time is always set to 0. 

Does this have an influence on training ?

**Comment by guanjunwu** [comment]
> In the function [readColmapCameras](https://github.com/hustvl/4DGaussians/blob/a2de1841756f49f7bf8d4b2f6fcad0ee5a8324ae/scene/dataset_readers.py#L116), i find that the time is always set to 0.
> 
> Does this have an influence on training ?

Oh, sorry, that's a bug. I will fix it soon.

**Comment by leo-frank** [comment]
I think this PR is correct.

**Comment by leo-frank** [comment]
But i am not sure about: whether if issue #35 (Loss become Nan after some time training) has relation with this bug ?
