### ISSUE TITLE
training using "cut_roasted_beef"

### ISSUE THREAD

**Issue by zdrac** [hustvl/4DGaussians#48]
Hello! I followed your instructions to preprocess the format of the "cut_roasted_beef" dataset for training. However, during the training process, the PSNR in evaluating tests consistently stays around 16 to 17. Why is this happening? Additionally, in order to train on this data, I uncommented this part in `dataset_readers.py`. Is this the correct approach? I hope to receive your assistance.
![image](https://github.com/hustvl/4DGaussians/assets/152582558/11e79b7d-3390-4f62-a2a7-3e79c52f708a)

**Comment by guanjunwu** [comment]
You can try :
`bash colmap.sh data/dynerf/cut_roasted_beef llff` to generate the sfm point firstly and then train the model.

**Comment by zdrac** [comment]
> You can try : `bash colmap.sh data/dynerf/cut_roasted_beef llff` to generate the sfm point firstly and then train the model.

Thanks for your reply! And I would also like to ask what frame rate you use to train the dynerf dataset to achieve the effects mentioned in the paper?

**Comment by guanjunwu** [comment]
first frame :)

**Comment by zdrac** [comment]
> first frame :)
e, how many photos are used to train for one camera to achieve the results in the paper? 300,150 or less?

**Comment by guanjunwu** [comment]
Only the first frame of each video(nearly 20?)



***@***.***
***@***.***







                       
Original Email
                       
                     

Sender:"zdrac"< ***@***.*** &gt;;

Sent Time:2023/12/15 10:51

To:"hustvl/4DGaussians"< ***@***.*** &gt;;

Cc recipient:"Geralt_of_Rivia"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [hustvl/4DGaussians] training using "cut_roasted_beef" (Issue#48)




  
first frame :)
 e, how many photos are used to train for one camera to achieve the results in the paper? 300,150 or less?

**Comment by zdrac** [comment]
OK. Thanks for your reply!

**Comment by chy2013920202** [comment]
> Oh, in dynerf, we use first 300 frames of each video, first video is used to validation and the others are used to train.
> 哦，在 dynerf 中，我们使用每个视频的前 300 帧， 第一个视频用于验证，其他视频用于训练。

Hello, may I ask how to modify the frame rate for training? For example, changing from 300 to 1000, thank you very much

**Comment by chy2013920202** [comment]
> Oh, in dynerf, we use first 300 frames of each video, first video is used to validation and the others are used to train.

I took 1200 frames and changed 300 to 1200, but found that the rendering effect was very poor. Do you know what's going on?
