### ISSUE TITLE
Data value requirements of the custom dataset

### ISSUE THREAD

**Issue by yifliu3** [hustvl/4DGaussians#49]
Thanks for your great work.

I'm trying your methods on a customized dataset obtained from stereoscopy rather than colmap or synthetic softwares. When preparing it for your code, a problem happens that HexPlane can not interpolate a value and returns zero vector. 

So I'm wondering if there is specific requirements of the input data range, like the poses should be centered or the initialized point cloud should be normalized or something else? Thanks.

**Comment by guanjunwu** [comment]
The size of the hexplane module depends on max and min value of initialized point clouds and `time` should be limited between [0,1]

**Comment by yifliu3** [comment]
Thanks a lot. Btw, is there any requirements of the point cloud? For example, should the initialized point cloud be transformed to the NDC coordinates, or just raw point clouds obtained in the world coordinate frame.

**Comment by guanjunwu** [comment]
you can check `colmap.sh`, I mainly use this script to generate the point clouds in the experiments of my paper.
