### ISSUE TITLE
About new code

### ISSUE THREAD

**Issue by ch1998** [hustvl/4DGaussians#50]
Hello！I have been following this project for a long time. I tested your old code and your new code, and there is a clear difference in the effect. You seem to have changed the deformation network, the floaters are significantly reduced, and the background is much cleaner.
But in some details, the old version of the model seems to be better, such as the hands in the picture below：
left is old code,right is new code

![image](https://github.com/hustvl/4DGaussians/assets/37291486/7c739ccc-fb9d-463a-bafa-fcab01f61254)

**Comment by guanjunwu** [comment]
you can follow the same hyperparameter settings as the old code, I believe it will achieve similar foreground results :)
besides, the reason why the background is cleaner is we compute the background point by colmap.
