### ISSUE TITLE
Error when run  comlap.sh on dynerf data

### ISSUE THREAD

**Issue by adkAurora** [hustvl/4DGaussians#52]
the problem happen after image_undistorter when doing patch_match_stereo

==============================================================================
Processing view 1 / 21 for r_012.png
==============================================================================

Reading inputs...
F1212 15:39:45.322880 972573 image.cc:58] Check failed: width_ == bitmap_.Width() (1352 vs. 2704) 
*** Check failure stack trace: ***
    @     0x7f52e2ddb1c3  google::LogMessage::Fail()
    @     0x7f52e2de025b  google::LogMessage::SendToLog()
    @     0x7f52e2ddaebf  google::LogMessage::Flush()
    @     0x7f52e2ddb6ef  google::LogMessageFatal::~LogMessageFatal()
    @     0x562ac73a7fec  colmap::mvs::Image::SetBitmap()
    @     0x562ac70f9ff8  colmap::mvs::PatchMatchController::ProcessProblem()
    @     0x562ac70fcec0  _ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultIvEES3_EZNS1_11_Task_stateISt5_BindIFMN6colmap3mvs20PatchMatchControllerEFvRKNSD_17PatchMatchOptionsEmEPSE_SF_mEESaIiEFvvEE6_M_runEvEUlvE_vEEE9_M_invokeERKSt9_Any_data
    @     0x562ac6fc2dbd  std::__future_base::_State_baseV2::_M_do_set()
    @     0x7f52e2dbc47f  __pthread_once_slow
    @     0x562ac70fd681  _ZNSt17_Function_handlerIFvvEZN6colmap10ThreadPool7AddTaskIMNS1_3mvs20PatchMatchControllerEFvRKNS4_17PatchMatchOptionsEmEJPS5_RS6_RmEEESt6futureINSt9result_ofIFT_DpT0_EE4typeEEOSG_DpOSH_EUlvE_E9_M_invokeERKSt9_Any_data
    @     0x562ac70f2f8a  colmap::ThreadPool::WorkerFunc()
    @     0x7f52cd3edaa3  execute_native_thread_routine
    @     0x7f52e2db3609  start_thread
    @     0x7f52cd0e3163  clone
colmap.sh: line 22: 972568 Aborted

**Comment by adkAurora** [comment]
how to run on dynerf data?  it seem in llff2colmap.py 158L, the image size are hard coded, (1352,1014)

**Comment by guanjunwu** [comment]
You can first run training scripts, it can extract images from the video and then run colmap.sh
