### ISSUE TITLE
colmap.sh for hypernerf dataset

### ISSUE THREAD

**Issue by mkjjang3598** [hustvl/4DGaussians#55]
Thank you for sharing your nice work! I have tried
`zsh colmap.sh ../data/hypernerf/vrig/vrig-chicken hypernerf`
to generate SFM dense points. In this part however, isn't filtering dynamic part using binary mask necessary in colmap? There is an option like `--Image_Reader.mask_path` in colmap feature_extractor. The implementation of above command gives abort error. And no points are triangulated as:
  => Image sees 0 / 0 points
  => Triangulated 0 points

**Comment by guanjunwu** [comment]
Hi,
The code is based assumption that the poses are known, so it's not necessary to mask the dynamic part. Meanwhile, I think leaving the dynamic part in the scene can also let the scripts generate some point clouds to inspire 4DGS's training.
And is that the data path of file is right? my data download scripts is 
`wget https://github.com/google/hypernerf/releases/download/v0.1/vrig_chicken.zip`

**Comment by mkjjang3598** [comment]
Thank you for your comments, I was using the same data as you provided. Still the point_triangulator fails.. What should I check? Colamap files (cameras.txt and images.txt) are build properly.

Besides, in database.py,
`assert camera_id == idList[i] `
gives an assertion error.

**Comment by guanjunwu** [comment]
Hi, can you provide the full logs when executing my scripts?
I reproduce the full process from another computer but it indeed can work orz
btw, can you generate the dense sfm point from anyother colmap format dataset? I.e:
```python
workdir=“data/nsff/Balloon1” # or any other colmap format dataset
echo $workdir
mkdir -p $workdir/dense/workspace
colmap image_undistorter --image_path $workdir/images_colmap --input_path $workdir/sparse/0 --output_path $workdir/dense/workspace
colmap patch_match_stereo --workspace_path $workdir/dense/workspace --workspace_format COLMAP --PatchMatchStereo.geom_consistency true
# colmap stereo_fusion --workspace_path $workdir/dense/workspace --output_path $workdir/dense/workspace/fused.ply
```

**Comment by mkjjang3598** [comment]
Hi, the test colmap using nsff dataset works. I've downloaded the hypernerf vrig-chicken dataset to ../data/hypernerf. So I use the following script
```
cd 4DGaussians
cd ../data/hypernerf
wget https://github.com/google/hypernerf/releases/download/v0.1/vrig_chicken.zip
unzip vrig_chicken
cd ../../4DGaussians
bash colmap.sh ../data/hypernerf/vrig-chicken hypernerf
```
This script generates empty points3D.txt file in sparse_custom folder.

**Comment by mkjjang3598** [comment]
I've missed a single line in colmap.sh
I've solved it by changing `export CUDA_VISIBLE_DEVICES=1` to `export CUDA_VISIBLE_DEVICES=0` as I was using a single GPU. 
Thanks!

**Comment by guanjunwu** [comment]
OMG thank you!
I've fixed it in the latest version.

**Comment by MasterBin-IIAU** [comment]
> Thank you for your comments, I was using the same data as you provided. Still the point_triangulator fails.. What should I check? Colmap files (cameras.txt and images.txt) are built properly.
> 
> Besides, in database.py, `assert camera_id == idList[i] ` gives an assertion error.

Hi everyone, I also encountered this assertion error when run colmap.sh. Any idea to solve it?

**Comment by MasterBin-IIAU** [comment]
I am using the latest code. My command is ``bash colmap.sh data/hypernerf/3dprinter hypernerf``. I had 138 images to perform feature_extractor and the results seemed to be normal. This error happened when run ``python database.py --database_path $workdir/colmap/database.db --txt_path $workdir/colmap/sparse_custom/cameras.txt``. Could you please give me some suggestions? Thanks! @mkjjang3598 @guanjunwu

**Comment by mkjjang3598** [comment]
Hi @MasterBin-IIAU!
To avoid assertion error, I have changed hypernerf2colmap.py file following the real colmap style. 

I changed this `print(idx,"SIMPLE_PINHOLE",image_size[0]/2,image_size[1]/2,cam['focal_length']/2,cam['principal_point'][0]/2,cam['principal_point'][1]/2,file=object_cameras_file)` to `print(idx+1,"SIMPLE_PINHOLE",image_size[0]/2,image_size[1]/2,cam['focal_length']/2,cam['principal_point'][0]/2,cam['principal_point'][1]/2,file=object_cameras_file)`

You might verify it by running the colmap (in gui using the same data) and checking cameras.bin and images.bin files.
