### ISSUE TITLE
Training on Custom Dataset from Video

### ISSUE THREAD

**Issue by andy-neparidze** [hustvl/4DGaussians#57]
Could you please provide instructions on how to create a dataset and train DGaussians using a custom video?

**Comment by guanjunwu** [comment]
please follow [nerfstudio](https://docs.nerf.studio/quickstart/custom_dataset.html) processing pipeline to generate colmap format dataset.
`ns-process-data video --data {DATA_PATH} --output-dir {PROCESSED_DATA_DIR}`
then using the training script to train a model.

**Comment by guanjunwu** [comment]
Hi, I've update the guidance for training from custom video, if you have any problem ,please reopen the issue and contact to me.
