### ISSUE TITLE
How to load checkpoint and continue training?

### ISSUE THREAD

**Issue by LDYang694** [hustvl/4DGaussians#59]
How should I continue to execute 20000 rounds of training (similar to finetune's idea) after the 20000 rounds of fine training have ended?

**Comment by guanjunwu** [comment]
I'm working on it, code will be updated soon!

**Comment by guanjunwu** [comment]
Hi, [this](https://github.com/hustvl/4DGaussians/pull/60) is a new PR.
I've checked it on the `bouncingballs`. I'd appreciate it if you could help me recheck it or use the code on your custom dataset.
