### ISSUE TITLE
Missing submodule

### ISSUE THREAD

**Issue by yhc-1** [hustvl/4DGaussians#6]
Hi, great work! I'm having trouble installing the submodule even I cloned with --recursive. Please help!

**Comment by henrypearce4D** [comment]
same issue, not found;

`https://github.com/hustvl/4DGaussians/blob/master/submodules/depth-diff-gaussian-rasterization`

**Comment by dlsrbgg33** [comment]
I think you can check [here](https://github.com/hustvl/4DGaussians/issues/2) for above issue.

**Comment by guanjunwu** [comment]
Thank you! I will fix the bug soon.
