### ISSUE TITLE
Question about COLMAP Init Points

### ISSUE THREAD

**Issue by BoMingZhao** [hustvl/4DGaussians#62]
Hi,
Thank you for your outstanding work! While running the HyperNeRF dataset, I noticed that I achieved a PSNR of 27.94, surpassing the reported 26.98 in your paper. Therefore, I would like to inquire if there might be an issue with my settings. In your code, you use every fourth image as training data, whereas COLMAP's image input is every nth image, ensuring that len(cam) // n is less than 200. Could this setting potentially impact the training results?

**Comment by guanjunwu** [comment]
I don't test that .... Estimating all points by input images are time-consuming and I (and my test computer) have no time to calculate all the sfm point from all the hypernerf dataset. I have to strike a balance between training speed(including preprocessing), rendering quality, and rendering speed.
But ensuring more input images will indeed perfrom a better sfm initialization.

**Comment by BoMingZhao** [comment]
Thanks for your reply!
By the way, I observed that initializing dynamic scene point clouds with COLMAP sometimes leads to matching points of the same object across multiple time frames, as shown below:

![lemon](https://github.com/hustvl/4DGaussians/assets/26064261/715a2928-4574-44ff-ad48-c87bb3f2e03d)
It's interesting because there won't be two lemons in the final rendered images. What could be the reason behind the 4D Gaussian effectively capturing the motion of redundant points?
