### ISSUE TITLE
Training on Custom Dataset process by nerfstudio 

### ISSUE THREAD

**Issue by shangchengPKU** [hustvl/4DGaussians#63]
thanks for ur great work, but when I follow the rule the problem emerged:
![scc](https://github.com/hustvl/4DGaussians/assets/23136796/79a25984-b6d7-46b6-84fd-1a59d08c7467)

**Comment by guanjunwu** [comment]
you should load the dataset as colmap format. 
meanwhile, there is a bug in colmap loading code, which causes a error in timestamp allocation. you can check the code and I'll update it in the next version.

**Comment by guanjunwu** [comment]
Hi, I've update the guidance in the tutoral, if you have any question, please reopen the issue and contact to me.
