### ISSUE TITLE
Equirectangular Projection in Rendering

### ISSUE THREAD

**Issue by hmermerkaya** [hustvl/4DGaussians#64]
Hello,
As fas as I know, in this repo, only perspective projection has been implemented in rendering. 
I was just wondering if  equirectangular projection is possible in rendering stage like in Nerfstudio, if so, do you guys think of implementing it? If not, can you give me some hint how to do that?
Thanks.

**Comment by guanjunwu** [comment]
Hi,
The rendering approach of 4D Gaussian-splatting primarily originates from the deformation field (which accomplishes the conversion from 3D Gaussian + time to 3D Gaussian), and the transformation of 3D Gaussian into a 2D image mainly depends on the rasterization algorithm. This algorithm is derived from 3D Gaussian Splatting (https://github.com/graphdeco-inria/gaussian-splatting). 
As far as I know, if you need to render in a different way, you might need to modify the CUDA code, which seems nobody has implemented yet.

**Comment by hmermerkaya** [comment]
Thanks for your reply
