### ISSUE TITLE
training in dynerf is failed

### ISSUE THREAD

**Issue by shangchengPKU** [hustvl/4DGaussians#67]
sry to bother u, when I put the dynerf dataset to train, first the train.py will extract the frame from video, but after that(and it seemed like the cam00 is lost) :
Traceback (most recent call last):
  File "train.py", line 417, in <module>
    training(lp.extract(args), hp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.expname)
  File "train.py", line 290, in training
    scene = Scene(dataset, gaussians, load_coarse=None)
  File "/mnt/data/shangcheng/4DGaussians/scene/__init__.py", line 53, in __init__
    scene_info = sceneLoadTypeCallbacks["dynerf"](args.source_path, args.white_background, args.eval)
  File "/mnt/data/shangcheng/4DGaussians/scene/dataset_readers.py", line 454, in readdynerfInfo
    eval_index=0,
  File "/mnt/data/shangcheng/4DGaussians/scene/neural_3D_dataset_NDC.py", line 254, in __init__
    self.load_meta()
  File "/mnt/data/shangcheng/4DGaussians/scene/neural_3D_dataset_NDC.py", line 268, in load_meta
    assert len(videos) == poses_arr.shape[0]
AssertionError

**Comment by guanjunwu** [comment]
Hi, after extracting image from video, you should delete the video file
It's a small bug in my scripts, and I'll fix it in the next version.

**Comment by pengcanon** [comment]
I think my question is related to this issue. 
After extracting frames from the videos and fixing a bug or two, training stops at dataset reading. It complains about not finding the 'points3D_downsample2.ply' file. Is that because colmap should run beforehand just like 3D Gaussian does? If so, can you suggest the format of the colmap output in the data folder?

**Comment by guanjunwu** [comment]
> l

Hi, you should run `colmap.sh` to compute dense point clouds.
then, use `python scripts/downsample_point.py data/dynerf/sear_steak/colmap/dense/workspace/fused.ply data/dynerf/sear_steak/points3D_downsample2.ply` to downsample the dense point clouds

**Comment by jsxzs** [comment]
@shangchengPKU @pengcanon You can look at the new [PR](https://github.com/hustvl/4DGaussians/pull/103), which provides instructions for training dynerf scenes.
