### ISSUE TITLE
Train on custom dataset without using NerfStudio

### ISSUE THREAD

**Issue by jiwencao** [hustvl/4DGaussians#69]
How can I train on custom dataset without using NerfStudio? Is there any instructions about preparing custom dataset which not using NerfStudio?

**Comment by guanjunwu** [comment]
Maybe you can follow 3D Gaussian Splatting's generation guidance?
It's mainly because camera poses should be computed by colmap, following nerfstudio can also allow you using other apps like poly cam.

**Comment by guanjunwu** [comment]
Hi, I've update the guidance in the 'readme.md', if you still have the similar problem, please reopen the issue and contact me.

**Comment by Harryhaozhu** [comment]
> 如何在不使用 NerfStudio 的情况下使用自定义数据集进行训练？是否有关于如何在不使用 NerfStudio 的情况下准备自定义数据集的说明？

您好，请问您自建数据集了吗，我自建数据集的时候，效果很差，因此我用公共数据集dynerf使用llff的imgs2poses.py生成了.npy，但是这个npy和官方提供的npy差距很大，请问您是如何生成的
