### ISSUE TITLE
Quality much lower than on project page

### ISSUE THREAD

**Issue by MrNeRF** [hustvl/4DGaussians#7]
Hi, 
thank you very much for your code and your research. I ran your code on the chickenchicken dataset. 
I used the follow (similar what you provide in the Readme) command for training:
```bash
python train.py -s data/hypernerf/interp/chickchicken --port 6017 --expname "hypternerf/interp/chickenchicken" --configs arguments/hypernerf/default.py
```
Took me approx. 1h to train on the dataset. Not sure, but the quality appears much worse to what you are presenting on the project page. I have also trained the synthetic bouncing ball dataset which also appears to me worse than what you show. Do I need to change something with respect to training parameters?

Here is the link to my result: https://youtube.com/shorts/hipsFRtWAz8?si=iF4OCXOVt2AZN0et

Btw, is there a way to view the dynamic scene interactively? For the the bouncingballs scene I can run SIBR viewer. However, I only have a static scene. For the chickenchicken Scene it crashes at SIBR viewer startup.

Thank you,
janusch

**Comment by guanjunwu** [comment]
Hi,
In the last version of the code(last commit), I found that the learning rate of the voxel grid didn't match our experimental setting. Then I fixed some bugs in the code. Can you pull the code again and run the experiment? I can also share the weight of the model with you :)

**Comment by MrNeRF** [comment]
Hi,
I am already on commit 4b181e2b343b76014da149f61c43f0978e5df9b8 so this is after the bugfix. 
If you could share the weights, it would be nice.

But lets assume I have only your code? How to get the results you are reporting? Or is there still a bug? Which version and configuration did you use to produce the reported outputs? 

Thank you!

**Comment by guanjunwu** [comment]
Hi,
[This](https://drive.google.com/file/d/1nh6z7KkfcgljceYfUktGL7xGq7gPHp2c/view?usp=share_link) is the training weight and training process of bouncingballs and chickchicken. You can use tensorboard to check the training process.
Meanwhile, when I run my code in the windows desktop (win11+RTX3080+cu121), the rendering quality indeed lower than results report in my paper, but I have no time to check the reason :(
Besh wishes!

**Comment by MrNeRF** [comment]
Hey, thank you. Its beyond what I have time for, but maybe someone else wants to help out.

**Comment by Tejasdavande07** [comment]
> Hi, thank you very much for your code and your research. I ran your code on the chickenchicken dataset. I used the follow (similar what you provide in the Readme) command for training:
> 
> ```shell
> python train.py -s data/hypernerf/interp/chickchicken --port 6017 --expname "hypternerf/interp/chickenchicken" --configs arguments/hypernerf/default.py
> ```
> 
> Took me approx. 1h to train on the dataset. Not sure, but the quality appears much worse to what you are presenting on the project page. I have also trained the synthetic bouncing ball dataset which also appears to me worse than what you show. Do I need to change something with respect to training parameters?
> 
> Here is the link to my result: https://youtube.com/shorts/hipsFRtWAz8?si=iF4OCXOVt2AZN0et
> 
> Btw, is there a way to view the dynamic scene interactively? For the the bouncingballs scene I can run SIBR viewer. However, I only have a static scene. For the chickenchicken Scene it crashes at SIBR viewer startup.
> 
> Thank you, janusch

Sir

please guide me I had done proper installation of set-up. 
now i am moving for the data-set training please provide me further steps to that properly.
i gone through readme.md but i face difficulty to understand please guide me for the process.
