### ISSUE TITLE
Training Error: Could not recognize scene type

### ISSUE THREAD

**Issue by kevinyu-0910** [hustvl/4DGaussians#71]
Thank you for your research. I am trying to train using a different dataset. I believe I have successfully loaded the dataset in the COLMAP format. However, when I run 
```
python train.py -s data/your-ns-data --port 6017 --expname "custom" --
configs arguments/hypernerf/default.py
```
I encounter the following error:
```
Traceback (most recent call last):
  File "train.py", line 416, in <module>
    training(lp.extract(args), hp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.expname)
  File "train.py", line 290, in training
    scene = Scene(dataset, gaussians, load_coarse=None)
  File "/data/data_2t/4DGaussians/scene/__init__.py", line 62, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!
```
I suspect that I might be missing a file like metadata.json found in the hypernerf dataset. Can you provide some guidance on how to resolve this issue?

**Comment by guanjunwu** [comment]
try to change it by `python train.py -s data/your-ns-data/colmap --port 6017 --expname "custom" --
configs arguments/hypernerf/default.py` ?

**Comment by Tejasdavande07** [comment]
> python train.py -s data/your-ns-data/colmap --port 6017 --expname "custom" -- configs arguments/hypernerf/default.py

i also faced the same problem

**Comment by guanjunwu** [comment]
Hi, I've update the guidance in the `readme.md`, if you still have the problem, please reopen the issue and contact me.

**Comment by outerelocarlos** [comment]
First of all, @guanjunwu thank you for your work on this project! Dynamic gaussian splatting is quite an interesting concept.

Having said that, I am running into the very same issue. In case it helps, here's how my data is structured:
```
clomp/
├── images/
│   ├── frame_000
│   ├── frame_001
│   ├── frame_002
│   └── ...
└── sparse/Ω/
    ├── cameras.bin
    ├── images.bin
    ├── points3D.bin
    └── project.ini
database.db
```
