### ISSUE TITLE
instructions on training on dynerf dataset

### ISSUE THREAD

**Issue by pengcanon** [hustvl/4DGaussians#73]
Sorry for opening a new issue as my followup question in a previous issue went unnoticed. 

I'm able to train on _dnerf_ dataset with no problems. But I seem to have trouble getting the _dynerf_ dataset in the right format. I did follow the tree structure as suggested in the readme file. Running the train.py on the dynerf dataset first of all extracts frames and organizes them into different folders. The code itself (possibly that of colmap too) has trivial bugs on image indexes that are easy to fix. But even after fixing them, I still ran into other issues:

  File "C:\Documents\GitHub\4DGaussians\scene\__init__.py", line 53, in __init__
    scene_info = sceneLoadTypeCallbacks["dynerf"](args.source_path, args.white_background, args.eval)
  File "C:\Documents\GitHub\4DGaussians\scene\dataset_readers.py", line 470, in readdynerfInfo
    pcd = fetchPly(ply_path)
  File "C:\Documents\GitHub\4DGaussians\scene\dataset_readers.py", line 125, in fetchPly
    plydata = PlyData.read(path)
  File "C:\Documents\GitHub\4DGaussians\venv\lib\site-packages\plyfile.py", line 498, in read
    (must_close, stream) = _open_stream(stream, 'read')
  File C:\Documents\GitHub\4DGaussians\venv\lib\site-packages\plyfile.py", line 657, in _open_stream
    return (True, open(stream, read_or_write[0] + 'b'))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Documents\\GitHub\\4DGaussians\\data\\dynerf\\cut_roasted_beef\\points3D_downsample2.ply'

I suspect it is because the files have not been arranged in the right format, additional to the format suggested in readme. Any suggestions?

Thank you

**Comment by guanjunwu** [comment]
Sorry for ignoring your issue, You can follow the preprocessing steps in the readme file.
![image](https://github.com/hustvl/4DGaussians/assets/87054407/2ed5bf33-538e-4369-b213-7334083072d0)

**Comment by pengcanon** [comment]
Thank you for your response. Can you be more specific about the tree structure of the data format? I wrote a program to extract each frame from each video and stored them in different folders named after the original video files like below:
├── data
│   | dynerf
│     ├── cook_spinach
│       ├── cam00
│         ├── images
│            ├──0000.png
│             ......
│       ├── cam01

When I then ran the bash file, it seems to only process the first image of every camera folder. This is not expected is it? Can you suggest on the data/file format that the train.py function expects after running colmap? For example, would it be like the following:
├── data
│   | dynerf
│     ├── cook_spinach
│       ├── cam00
│         ├── images
│            ├──0000.png
│             :
│             :
│         ├── sparse(result of running colmap)
│         ├── dense(result of running colmap)
│       ├── cam01
│        : 
│        :

**Comment by guanjunwu** [comment]
That's true. I indeed only use the first frame of each video to generate point clouds of whole scene.
The purpose is to generate far-distance point clouds, the motion of the point(3D Gaussians) will be learned by the Gaussian deformation field.

**Comment by jsxzs** [comment]
@pengcanon Hi, you can refer to the issue #98 . It may help you.

**Comment by pengcanon** [comment]
Thank you. The model can train on dynerf data with the instructions on data preprocessing.
