### ISSUE TITLE
Got bit confused about the Gaussian deformation field network

### ISSUE THREAD

**Issue by darthandvader** [hustvl/4DGaussians#77]
From the paper we know the input of Gaussian deformation field network is 3D gaussians and time stamp, I wonder if these gaussians all come from the initial point clouds file or you guys just generate different point clouds files at different timestamp and use the data to predict the deformation of gaussians? Just a bit confused about here, thank you!

**Comment by guanjunwu** [comment]
Thanks for your problem!
Indeed, all the 3D Gaussians comes from the initialized point clouds, only one set of 3D Gaussians maintained, Gaussian deformation networks will predict each 3D Gaussians deformation (poisition, scaling, rotations even opacity and color if you want) as any desired timestamp. But we also follow 3DGS's approach to pruning and densify 3D Gaussians during the optimization, so the final numbers of 3D Gaussians maybe more or less than initialized 3D Gaussians.

**Comment by darthandvader** [comment]
What I'm confused about is in the paper it seems to encode the only one set of 3D gaussians (which is static right?) and timestamp into hexplanes but without the deformation information. I'm trying to understand how this deformation network utilizes images frames at different timestamp and predict the gaussian deformation.

**Comment by guanjunwu** [comment]
It only takes 3D Gaussians' position and timestamp as input, then predict the Gaussian's deformation at this timestamp. Then differential 3D Gaussian rasterization can be used as the same purpose.
So I think this one set of 3D Gaussians stands for geometry, and the deformation field will control geometry's motion.

**Comment by RNGrunshen** [comment]
> It only takes 3D Gaussians' position and timestamp as input, then predict the Gaussian's deformation at this timestamp. Then differential 3D Gaussian rasterization can be used as the same purpose. So I think this one set of 3D Gaussians stands for geometry, and the deformation field will control geometry's motion.


Hello, thank you very much for your outstanding work! I have carefully read your paper and code, but due to the large amount of code, there are some details I did not understand and hope you can help me clarify:

The paper mentions that we only need to maintain the initial 3D Gaussians, and other frames' 3D Gaussians can be obtained by querying time t. The initial 3D Gaussians seem to be the initial static scene, How does the deformation field predict the future movements of the initial 3D Gaussians? Does the initial 3D Gaussian contain any temporal information?

**Comment by guanjunwu** [comment]
> > It only takes 3D Gaussians' position and timestamp as input, then predict the Gaussian's deformation at this timestamp. Then differential 3D Gaussian rasterization can be used as the same purpose. So I think this one set of 3D Gaussians stands for geometry, and the deformation field will control geometry's motion.
> 
> Hello, thank you very much for your outstanding work! I have carefully read your paper and code, but due to the large amount of code, there are some details I did not understand and hope you can help me clarify:
> 
> The paper mentions that we only need to maintain the initial 3D Gaussians, and other frames' 3D Gaussians can be obtained by querying time t. My questions are:
> 
> 1. The initial 3D Gaussians seem to be the initial static scene, How does the deformation field predict the future movements of the initial 3D Gaussians? Does the initial 3D Gaussian contain any temporal information?
> 2. Could you please provide a detailed explanation of the process of 4D Gaussian Joint Optimization? Does this optimization process simultaneously optimize the deformation field and the initial 3D Gaussians?
> 
> I'm looking forward to your reply. Thank you😃!

Hi, thanks for you nice work!
1. There are no any time-aware information in the initialized 3D Gaussians. However, we can use the model to predict any 3D Gaussians's motion. Each 3D Gaussians are composed with position(x,y,z), scaling, rotation, opacity and colors. I've tried lots of methods to let the deformation network to understand 3D Gaussians, but the best method I think is only take 3D Gaussians' position as input. Therefore,  the input `xyz` could be treated 3D Gaussians spatial position, which could stand for a 3D Gaussians.
2. Joint optimization is easy, all the color is rasterized by deformed 3D Gaussians, so the gradient can be convert to the Gaussian deformation network and the position of 3D Gaussians. So during the training, the parameters of 3D Gaussians and the Gaussian deformation network will be optimized.
