### ISSUE TITLE
Coarse "render_process" using fine standard

### ISSUE THREAD

**Issue by baitingzbt** [hustvl/4DGaussians#79]
When `render_process` runs at coarse stage, I think the stage is actually passed in as `coarsetrain` or `coarsetest`, which causes the `gaussian_renderer` believe it should follow the fine-stage standard. Is this intended?

Here returns false, perhaps need a `start.startswith('coarse')`:
https://github.com/hustvl/4DGaussians/blob/d412f8b22d107f65961c334f594dea81f6338580/gaussian_renderer/__init__.py#L80

Here is where stage being passed in:
https://github.com/hustvl/4DGaussians/blob/d412f8b22d107f65961c334f594dea81f6338580/train.py#L239

**Comment by guanjunwu** [comment]
thank you for pointing out the bugs!
in fact, it maybe should be changed to 
`if "coarse" in stage`

**Comment by guanjunwu** [comment]
Hi, i've solve the problem in the latest version. Please feel free to contact me if you have other problem.
