### ISSUE TITLE
Broom Scene Rendering

### ISSUE THREAD

**Issue by jypppppp** [hustvl/4DGaussians#88]
https://github.com/hustvl/4DGaussians/assets/64428904/ffd91ea8-31f7-47f6-8386-395fba128979

**Comment by jypppppp** [comment]
Hi, thanks for the amazing work! I was trying to render the video and I got a very strange one. But evaluation results are consistent withe the reported one in the paper. Are there any problems with the render.py file?

Thanks,
Jason

**Comment by guanjunwu** [comment]
Hi, thanks for your question!
In the virg datasets, all the images are captured by two cameras (one timestamp has two images). So the rendered video is the same as the dataset.
To solve the problem, you can just extract half of its frames(such as only render odd index of poses).
Hope this may help you.
Best,
Guanjun
