### ISSUE TITLE
Recommended Setup/Instructions to Run on Custom data?

### ISSUE THREAD

**Issue by x-CK-x** [hustvl/4DGaussians#9]
I'm curious what needs to change relative to the existing instructions on the README in order to use my own data?

**Comment by guanjunwu** [comment]
Hi,
maybe like this:
1. Downloading nerfstudio `pip install nerfstudio`
2. using `ns-process-data` to convert data into `blender` format
3. split data into "transforms_train", "transforms_test", "transforms_val" ( I have not finished using data for only training yet, you can write the code and create a pr o.O)
btw, the pose calculated by colmap is not precise so rendering quality may not good enough, free-view rendering may cannot work well as you imaging.

**Comment by taoranyi** [comment]
Thank you for your attention. You can use the [colab](https://colab.research.google.com/github/google/nerfies/blob/main/notebooks/Nerfies_Capture_Processing.ipynb#scrollTo=T2xqbzxILqZO) from [nerfies](https://github.com/google/nerfies)

**Comment by x-CK-x** [comment]
> Hi, maybe like this:
> 
>     1. Downloading nerfstudio `pip install nerfstudio`
> 
>     2. using `ns-process-data` to convert data into `blender` format
> 
>     3. split data into "transforms_train", "transforms_test", "transforms_val" ( I have not finished using data for only training yet, you can write the code or adding the guidance of using custom data and create a pr o.O)
>        btw, the pose calculated by colmap is not precise so rendering quality may not good enough, free-view rendering may cannot work well as you imaging.

I've also noticed issues with colmap in the past regarding the pose. I don't suppose there's a direct replacement for colmap yet is there?

**Comment by guanjunwu** [comment]
Yes, thank you for the notation :)

**Comment by camtrik** [comment]
Hi, @taoranyi
It seems [colab](https://colab.research.google.com/github/google/nerfies/blob/main/notebooks/Nerfies_Capture_Processing.ipynb#scrollTo=T2xqbzxILqZO) from [nerfies](https://github.com/google/nerfies) can generate most of the required files from custom data, but not points.npy, which is required in 4D Gaussians code. 
Any way to generate this file? Or is it necessary for training the 4D Gaussian?

**Comment by taoranyi** [comment]
Hello camtrik! You can use (this method)[https://github.com/hustvl/4DGaussians/blob/a2de1841756f49f7bf8d4b2f6fcad0ee5a8324ae/scene/dataset_readers.py#L449] to randomly initialize instead of using points.npy.

**Comment by Tejasdavande07** [comment]
Hi I was getting below mentioned error - 


(Gaussians4D) F:\Standalones\test\4DGaussians>python train.py -s data/hypernerf/interp/bouncingballs --port 6017 --expname "hypternerf/interp/bouncingballs" --configs arguments/hypernerf/default.py


Traceback (most recent call last):
  File "F:\Standalones\test\4DGaussians\train.py", line 17, in <module>
    from gaussian_renderer import render, network_gui
  File "F:\Standalones\test\4DGaussians\gaussian_renderer\__init__.py", line 15, in <module>
    from scene.gaussian_model import GaussianModel
  File "F:\Standalones\test\4DGaussians\scene\__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "F:\Standalones\test\4DGaussians\scene\dataset_readers.py", line 26, in <module>
    from plyfile import PlyData, PlyElement
ModuleNotFoundError: No module named 'plyfile'

**Comment by guanjunwu** [comment]
`

> Hi I was getting below mentioned error -
> 
> (Gaussians4D) F:\Standalones\test\4DGaussians>python train.py -s data/hypernerf/interp/bouncingballs --port 6017 --expname "hypternerf/interp/bouncingballs" --configs arguments/hypernerf/default.py
> 
> Traceback (most recent call last): File "F:\Standalones\test\4DGaussians\train.py", line 17, in from gaussian_renderer import render, network_gui File "F:\Standalones\test\4DGaussians\gaussian_renderer__init__.py", line 15, in from scene.gaussian_model import GaussianModel File "F:\Standalones\test\4DGaussians\scene__init__.py", line 16, in from scene.dataset_readers import sceneLoadTypeCallbacks File "F:\Standalones\test\4DGaussians\scene\dataset_readers.py", line 26, in from plyfile import PlyData, PlyElement ModuleNotFoundError: No module named 'plyfile'

maybe `pip install plyfile` may work?

**Comment by Tejasdavande07** [comment]
> pip install plyfile

Now getting this issue.

(Gaussians4D) F:\Standalones\test\4DGaussians>python train.py -s data/hypernerf/interp/bouncingballs --port 6017 --expname "hypternerf/interp/bouncingballs" --configs arguments/hypernerf/default.py
Traceback (most recent call last):
  File "F:\Standalones\test\4DGaussians\train.py", line 328, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'

**Comment by guanjunwu** [comment]
> > pip install plyfile
> 
> Now getting this issue.
> 
> (Gaussians4D) F:\Standalones\test\4DGaussians>python train.py -s data/hypernerf/interp/bouncingballs --port 6017 --expname "hypternerf/interp/bouncingballs" --configs arguments/hypernerf/default.py Traceback (most recent call last): File "F:\Standalones\test\4DGaussians\train.py", line 328, in import mmcv ModuleNotFoundError: No module named 'mmcv'

I guess that you didn't use `pip install -r requirements.txt` to install relative package firstly :)

**Comment by Tejasdavande07** [comment]
> > > pip install plyfile
> > 
> > 
> > Now getting this issue.
> > (Gaussians4D) F:\Standalones\test\4DGaussians>python train.py -s data/hypernerf/interp/bouncingballs --port 6017 --expname "hypternerf/interp/bouncingballs" --configs arguments/hypernerf/default.py Traceback (most recent call last): File "F:\Standalones\test\4DGaussians\train.py", line 328, in import mmcv ModuleNotFoundError: No module named 'mmcv'
> 
> I guess that you didn't use `pip install -r requirements.txt` to install relative packages firstly :)

done the changes but still getting below mentioned error -

(Gaussians4D) F:\Standalones\test\4DGaussians>python train.py -s data/hypernerf/interp/bouncingballs --port 6017 --expname "hypternerf/interp/bouncingballs" --configs arguments/hypernerf/default.py
Optimizing
Output folder: ./output/hypternerf/interp/bouncingballs [21/10 14:30:41]
feature_dim: 64 [21/10 14:30:41]
Traceback (most recent call last):
  File "F:\Standalones\test\4DGaussians\train.py", line 340, in <module>
    training(lp.extract(args), hp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.expname)
  File "F:\Standalones\test\4DGaussians\train.py", line 224, in training
    scene = Scene(dataset, gaussians, load_coarse=None)
  File "F:\Standalones\test\4DGaussians\scene\__init__.py", line 55, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!


Please suggest how to process for the data training if  you have the file data testing please share so that I can check for the same.

**Comment by guanjunwu** [comment]
Please check your input:
`--expname "hypternerf/interp/bouncingballs" `

**Comment by guanjunwu** [comment]
> > > > pip install plyfile
> > > 
> > > 
> > > Now getting this issue.
> > > (Gaussians4D) F:\Standalones\test\4DGaussians>python train.py -s data/hypernerf/interp/bouncingballs --port 6017 --expname "hypternerf/interp/bouncingballs" --configs arguments/hypernerf/default.py Traceback (most recent call last): File "F:\Standalones\test\4DGaussians\train.py", line 328, in import mmcv ModuleNotFoundError: No module named 'mmcv'
> > 
> > 
> > I guess that you didn't use `pip install -r requirements.txt` to install relative packages firstly :)
> 
> done the changes but still getting below mentioned error -
> 
> (Gaussians4D) F:\Standalones\test\4DGaussians>python train.py -s data/hypernerf/interp/bouncingballs --port 6017 --expname "hypternerf/interp/bouncingballs" --configs arguments/hypernerf/default.py Optimizing Output folder: ./output/hypternerf/interp/bouncingballs [21/10 14:30:41] feature_dim: 64 [21/10 14:30:41] Traceback (most recent call last): File "F:\Standalones\test\4DGaussians\train.py", line 340, in training(lp.extract(args), hp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.expname) File "F:\Standalones\test\4DGaussians\train.py", line 224, in training scene = Scene(dataset, gaussians, load_coarse=None) File "F:\Standalones\test\4DGaussians\scene__init__.py", line 55, in **init** assert False, "Could not recognize scene type!" AssertionError: Could not recognize scene type!
> 
> Please suggest how to process for the data training if you have the file data testing please share so that I can check for the same.


Please check your input:
--expname "hypternerf/interp/bouncingballs"

**Comment by Tejasdavande07** [comment]
Now in my input side issue was their right?
please share file for input from data folder to run for testing by using command. 
 share the command to run.

**Comment by guanjunwu** [comment]
please follow `readme.md` to set up your environment and prepare your dataset **step by step** carefully :) 
"bouncingballs" is in datasets of **dnerf** instead of "hypternerf" ("hypernerf" exactly)

**Comment by Tejasdavande07** [comment]
> please follow `readme.md` to set up your environment and prepare your dataset **step by step** carefully :) "bouncingballs" is in datasets of **dnerf** instead of "hypternerf" ("hypernerf" exactly)

Thanks for suggestion.
actually I was quite confuse in which data-set i have to use thier is lot of reference things are available in readme.md.
for my better understanding please guide me the step for creation of data set for training to output of video.
It helps all those who are come here to see commet.

Thanks

**Comment by Harryhaozhu** [comment]
> 你好 camtrik！你可以使用（此方法）[https://github.com/hustvl/4DGaussians/blob/a2de1841756f49f7bf8d4b2f6fcad0ee5a8324ae/scene/dataset_readers.py#L449] 来随机初始化，而不是使用 points.npy。

请问这个如何实现，谢谢

**Comment by Harryhaozhu** [comment]
> 你好，[@taoranyi](https://github.com/taoranyi) 看起来[nerfies](https://github.com/google/nerfies)的[colab](https://colab.research.google.com/github/google/nerfies/blob/main/notebooks/Nerfies_Capture_Processing.ipynb#scrollTo=T2xqbzxILqZO)可以根据自定义数据生成大部分所需文件，但无法生成 points.npy 文件，而 4D 高斯函数代码需要用到这个文件。 有什么方法可以生成这个文件吗？或者说，训练 4D 高斯函数是否必须用到这个文件？[](https://github.com/google/nerfies)

您好，有解决办法了吗，我也遇到了这个问题
