### ISSUE TITLE
如何查看训练完的模型？

### ISSUE THREAD

**Issue by Huotianci** [hustvl/4DGaussians#97]
尊敬的作者您好：
  我已经完成对您代码的复现，您做的工作非常的出色！！！

  但是我现在只能在模型训练的时候，查看它渲染的效果，请问对于训练好的模型我应该如何查看它呢？

  再次感谢您所做的工作！！！
  期待您的回复！祝好！

**Comment by Huotianci** [comment]
对于训练完的模型，我用的是下面的命令：
viewers/bin/SIBR_gaussianViewer_app.exe -m output/dnerf/bouncingballs/

**Comment by Huotianci** [comment]
结果是这样：
![image](https://github.com/hustvl/4DGaussians/assets/88657565/85d9c533-102f-46ee-878c-25184d4e91ee)

**Comment by guanjunwu** [comment]
你好，我目前的代码中没有实现对这个viewer的支持，这个viewer只读进去了canonical的3dgs，并没有读入deformation. 我建议你可以开一个训练脚本，把iteration稍微延长一点（比如20010）。然后提前把viewer打开，这样他就会卡在20000步了。
（不过目前的viewer效果十分的初步，后面我会支持更加好的viewer

**Comment by Huotianci** [comment]
好的谢谢！！！
