### ISSUE TITLE
Colmap.sh error in own data processing

### ISSUE THREAD

**Issue by astergasp** [hustvl/4DGaussians#98]
Hey there!

Thanks a lot for the work you shared. I had a lot of fun exploring it! I successfully tried the synthetic scenes, but I encountered errors when it came to the scenes with real footage. I wonder if someone can give me advice or clues on how to solve the errors I encounter in the process.

Here is the stage I'm stuck at:

My folder structure is:

├── data
│   │dynerf
│     ├── cook_spinach
│       ├ poses_bounds.npy
│       ├── cam00
│           ├── images
│               ├── 0000.png
│               ├── 0001.png
│               ├── 0002.png
│               ├── ...
│       ├── cam01
│           ├── images
│               ├── 0000.png
│               ├── 0001.png
│               ├── ...

I run the command: 

(Gaussians4D) C:\Users\Aster\4DGaussians>bash colmap.sh C:/Users/Aster/4DGaussians/data/dynerf/cook_spinach llff
Traceback (most recent call last):
  File "scripts/llff2colmap.py", line 96, in <module>
    assert len(videos) == poses_arr.shape[0]
AssertionError
cp: cannot stat 'C:/Users/Aster/4DGaussians/data/dynerf/cook_spinach/image_colmap': No such file or directory
colmap.sh: line 15: colmap: command not found
ERROR: database path dosen't exist -- please check database.db.
colmap.sh: line 17: colmap: command not found
colmap.sh: line 20: colmap: command not found
colmap.sh: line 23: colmap: command not found
colmap.sh: line 24: colmap: command not found
colmap.sh: line 25: colmap: command not found

Does someone else's as also face this problem ?

**Comment by guanjunwu** [comment]
sry for that, maybe you should remove all the original videos such as `cam00.mp4`-`cam19.mp4`.
this is a bug in my code, I will fix it soon :)

**Comment by astergasp** [comment]
They are already removed from the folder.
Maybe I missed a step or do I need to specify something in the Colmap command?

**Comment by yangqing-yq** [comment]
> They are already removed from the folder. Maybe I missed a step or do I need to specify something in the Colmap command?

hey, have you solve the issue?
I encounter the same issue, and stuck here 。。

**Comment by jsxzs** [comment]
@yangqing-yq @astergasp You can look at the new [PR](https://github.com/hustvl/4DGaussians/pull/103), which has solved problems of preprocessing dynerf scenes and provides instructions for training dynerf scenes.

**Comment by jsxzs** [comment]
> > @yangqing-yq @astergasp You can look at the new [PR](https://github.com/hustvl/4DGaussians/pull/103), which has solved problems of preprocessing dynerf scenes and provides instructions for training dynerf scenes.
> 
> Hi!I have added and modified the code according to the method you gave, but after getting the frames of each video, and then executing bash colmap.sh data/dynerf/cut_roasted_beef llff, the following error still occurs. ![image](https://private-user-images.githubusercontent.com/147734830/313674197-08df84e2-d611-43dd-941e-22707048b328.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NjQ4NzcsIm5iZiI6MTcxMDc2NDU3NywicGF0aCI6Ii8xNDc3MzQ4MzAvMzEzNjc0MTk3LTA4ZGY4NGUyLWQ2MTEtNDNkZC05NDFlLTIyNzA3MDQ4YjMyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMjIyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDVlNzlkNGQwY2M3ZGQ4MmY4NjdmYjcxNDI4Zjk4OWYyYWFkYWFlNmZiMTFiZjMzNTIzZTVhNTJiYTQyOTM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w1aS3GbCCT3jf-xdfVT1dAKM7Sd8a6evHfY4h-syeZI)

Can you give more information about the error? Is it an `AssertionError`?

**Comment by LongJi12** [comment]
> > Hey there!
> > Thanks a lot for the work you shared. I had a lot of fun exploring it! I successfully tried the synthetic scenes, but I encountered errors when it came to the scenes with real footage. I wonder if someone can give me advice or clues on how to solve the errors I encounter in the process.
> > Here is the stage I'm stuck at:
> > My folder structure is:
> > ├── data │ │dynerf │ ├── cook_spinach │ ├ poses_bounds.npy │ ├── cam00 │ ├── images │ ├── 0000.png │ ├── 0001.png │ ├── 0002.png │ ├── ... │ ├── cam01 │ ├── images │ ├── 0000.png │ ├── 0001.png │ ├── ...
> > I run the command:
> > (Gaussians4D) C:\Users\Aster\4DGaussians>bash colmap.sh C:/Users/Aster/4DGaussians/data/dynerf/cook_spinach llff Traceback (most recent call last): File "scripts/llff2colmap.py", line 96, in assert len(videos) == poses_arr.shape[0] AssertionError cp: cannot stat 'C:/Users/Aster/4DGaussians/data/dynerf/cook_spinach/image_colmap': No such file or directory colmap.sh: line 15: colmap: command not found ERROR: database path dosen't exist -- please check database.db. colmap.sh: line 17: colmap: command not found colmap.sh: line 20: colmap: command not found colmap.sh: line 23: colmap: command not found colmap.sh: line 24: colmap: command not found colmap.sh: line 25: colmap: command not found
> > Does someone else's as also face this problem ?
> 
> @LongJi12 Is your error the same as this? If yes, it is actually an AssertionError in `llff2colmap.py`. Do you modify the code in `llff2colmap.py` as my PR suggests?

Yes, my error is similar to this, and I also modified it according to your suggestion，such as

**Comment by LongJi12** [comment]
> > Hey there!
> > Thanks a lot for the work you shared. I had a lot of fun exploring it! I successfully tried the synthetic scenes, but I encountered errors when it came to the scenes with real footage. I wonder if someone can give me advice or clues on how to solve the errors I encounter in the process.
> > Here is the stage I'm stuck at:
> > My folder structure is:
> > ├── data │ │dynerf │ ├── cook_spinach │ ├ poses_bounds.npy │ ├── cam00 │ ├── images │ ├── 0000.png │ ├── 0001.png │ ├── 0002.png │ ├── ... │ ├── cam01 │ ├── images │ ├── 0000.png │ ├── 0001.png │ ├── ...
> > I run the command:
> > (Gaussians4D) C:\Users\Aster\4DGaussians>bash colmap.sh C:/Users/Aster/4DGaussians/data/dynerf/cook_spinach llff Traceback (most recent call last): File "scripts/llff2colmap.py", line 96, in assert len(videos) == poses_arr.shape[0] AssertionError cp: cannot stat 'C:/Users/Aster/4DGaussians/data/dynerf/cook_spinach/image_colmap': No such file or directory colmap.sh: line 15: colmap: command not found ERROR: database path dosen't exist -- please check database.db. colmap.sh: line 17: colmap: command not found colmap.sh: line 20: colmap: command not found colmap.sh: line 23: colmap: command not found colmap.sh: line 24: colmap: command not found colmap.sh: line 25: colmap: command not found
> > Does someone else's as also face this problem ?
> 
> @LongJi12 Is your error the same as this? If yes, it is actually an AssertionError in `llff2colmap.py`. Do you modify the code in `llff2colmap.py` as my PR suggests?

Yes, my error is similar to this, and I also modified it according to your suggestion，such as


![image](https://github.com/hustvl/4DGaussians/assets/147734830/3e848faf-858f-43a9-b5db-d5195036e68e)

**Comment by jsxzs** [comment]
@LongJi12 So what is your error? Can you give more specific error information so that we can help you work out the problem?

**Comment by yangqing-yq** [comment]
> @yangqing-yq @astergasp You can look at the new [PR](https://github.com/hustvl/4DGaussians/pull/103), which has solved problems of preprocessing dynerf scenes and provides instructions for training dynerf scenes.

it worked! Thanks!

**Comment by yangqing-yq** [comment]
it worked! Thanks!

**Comment by astergasp** [comment]
Hey guys, 
I've been away for some days, i happy to see all those answer and glad that it works for some of you !
On my side it tried the fix and i still have the : ERROR: database path dosen't exist -- please check database.db

Reinstalled the repo from scratch, run the lego to see if my install works well (and it worked). Then i moved  on the cook_spinach scenes following the command updated in the readme. Pre-processing works well, i removed the .mp4 files to avoid problem (just in case) and run the command : 

bash colmap.sh data/dynerf/cook_spinach llff
['data/dynerf/cook_spinach\\cam00\\images\\0000.png',
[...]
'data/dynerf/cook_spinach\\cam20\\images\\0000.png']
['r_000', 'png']
[...]
['r_020', 'png']
[[[ 9.99169516e-01  2.85731534e-02 -2.90491673e-02  2.58082050e-02]
  [ 2.54924999e-02 -9.94520241e-01 -1.01388470e-01 -1.33043565e+00]
  [-3.17869732e-02  1.00563733e-01 -9.94422709e-01 -2.15670801e-01]]
[...]
 [[ 9.04287962e-01 -1.23696495e-01 -4.08610401e-01 -5.70014799e+00]
  [-6.01713554e-02 -9.84479480e-01  1.64862247e-01  1.35437686e+00]
  [-4.22661437e-01 -1.24496304e-01 -8.97695928e-01  9.25457687e-01]]]
colmap.sh: line 15: colmap: command not found
ERROR: database path dosen't exist -- please check database.db.
colmap.sh: line 17: colmap: command not found
colmap.sh: line 20: colmap: command not found
colmap.sh: line 23: colmap: command not found
colmap.sh: line 24: colmap: command not found
colmap.sh: line 25: colmap: command not found

Maybe some of you have been able to run it successfully on your side can give me advise ?

**Comment by chy2013920202** [comment]
> Hey guys, 嘿,伙计们 I've been away for some days, i happy to see all those answer and glad that it works for some of you !我已经离开好几天了，我很高兴看到所有这些答案，也很高兴这对你们中的一些人有用！ On my side it tried the fix and i still have the : ERROR: database path dosen't exist -- please check database.db在我这边，它尝试了修复程序，但我仍然有：错误：数据库路径不存在 - 请检查database.db
> 
> Reinstalled the repo from scratch, run the lego to see if my install works well (and it worked). Then i moved on the cook_spinach scenes following the command updated in the readme. Pre-processing works well, i removed the .mp4 files to avoid problem (just in case) and run the command :从头开始重新安装存储库，运行 lego 以查看我的安装是否运行良好（并且它有效）。然后我按照自述文件中更新的命令继续cook_spinach场景。预处理效果很好，我删除了 .mp4 文件以避免出现问题（以防万一）并运行命令：
> 
> bash colmap.sh data/dynerf/cook_spinach llffbash colmap.sh data/dynasty/llff cook_spinach ['data/dynerf/cook_spinach\cam00\images\0000.png',['data/dynerf/cook_spinach\cam00\images\0000.png'， [...] 'data/dynerf/cook_spinach\cam20\images\0000.png'] ['r_000', 'png'] ['r_000'， 'png'] [...] ['r_020', 'png'] ['r_020'， 'png'] [[[ 9.99169516e-01 2.85731534e-02 -2.90491673e-02 2.58082050e-02][[[ 9.99169516e-01 2.85731534e-02 -2.90491673e-02 2.58082050e-02] [ 2.54924999e-02 -9.94520241e-01 -1.01388470e-01 -1.33043565e+00] [-3.17869732e-02 1.00563733e-01 -9.94422709e-01 -2.15670801e-01]][-3.17869732e-02 1.00563733e-01 -9.94422709e-01 -2.15670801e-01]] [...] [[ 9.04287962e-01 -1.23696495e-01 -4.08610401e-01 -5.70014799e+00] [-6.01713554e-02 -9.84479480e-01 1.64862247e-01 1.35437686e+00][-6.01713554e-02 -9.84479480e-01 1.64862247e-01 1.35437686e+00] [-4.22661437e-01 -1.24496304e-01 -8.97695928e-01 9.25457687e-01]]][-4.22661437e-01 -1.24496304e-01 -8.97695928e-01 9.25457687e-01]]] colmap.sh: line 15: colmap: command not foundcolmap.sh：第 15 行：colmap：找不到命令 ERROR: database path dosen't exist -- please check database.db.错误：数据库路径不存在 -- 请检查database.db。 colmap.sh: line 17: colmap: command not foundcolmap.sh：第 17 行：colmap：找不到命令 colmap.sh: line 20: colmap: command not foundcolmap.sh：第 20 行：colmap：找不到命令 colmap.sh: line 23: colmap: command not foundcolmap.sh：第 23 行：colmap：找不到命令 colmap.sh: line 24: colmap: command not foundcolmap.sh：第 24 行：colmap：找不到命令 colmap.sh: line 25: colmap: command not foundcolmap.sh：第 25 行：colmap：找不到命令
> 
> Maybe some of you have been able to run it successfully on your side can give me advise ?
Please download colmap and add its bin file to the system environment variable path, such as
![image](https://github.com/user-attachments/assets/75bc951e-5b96-474a-8bf5-8335ba3dc705)

**Comment by chy2013920202** [comment]
> I changed the code and installed colmap, but the same error still occurs, can you give me some advice?我修改了代码并安装了 colmap，但还是出现同样的错误，你能给我一些建议吗？

Maybe you haven't set environment variables? Please refer to the previous reply

**Comment by ihuchao** [comment]
Thanks a lot, I restarted my computer, and it worked.

**Comment by ihuchao** [comment]
> > I changed the code and installed colmap, but the same error still occurs, can you give me some advice?我修改了代码并安装了 colmap，但还是出现同样的错误，你能给我一些建议吗？
> 
> Maybe you haven't set environment variables? Please refer to the previous reply

Thanks a lot, I restarted my computer, and it worked.

**Comment by hhxphh** [comment]
I use newest code and installed colmap, but the same error occurs。。。so sad
xhz@DESKTOP-SREEJNL MINGW64 /e/Last/meeting/code/4DGaussians (master)
$ bash colmap.sh E:/Last/meeting/code/3DGStream/dataset/flame_steak llff
['E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam00\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam01\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam02\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam03\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam04\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam05\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam06\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam07\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam08\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam09\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam10\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam11\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam12\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam13\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam14\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam15\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam16\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam17\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam18\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam19\\images\\0000.png', 'E:/Last/meeting/code/3DGStream/dataset/flame_steak\\cam20\\images\\0000.png']
['r_000', 'png']
['r_001', 'png']
['r_002', 'png']
['r_003', 'png']
['r_004', 'png']
['r_005', 'png']
['r_006', 'png']
['r_007', 'png']
['r_008', 'png']
['r_009', 'png']
['r_010', 'png']
['r_011', 'png']
['r_012', 'png']
['r_013', 'png']
['r_014', 'png']
['r_015', 'png']
['r_016', 'png']
['r_017', 'png']
['r_018', 'png']
['r_019', 'png']
['r_020', 'png']
[[[ 9.99086977e-01  2.87201983e-02 -3.16285146e-02  3.23124293e-02]
  [ 2.53667512e-02 -9.94486361e-01 -1.01751686e-01 -1.32855716e+00]
  [-3.43764550e-02  1.00856472e-01 -9.94306910e-01 -2.15579018e-01]]

 [[ 8.38798298e-01  2.84471710e-02  5.43698605e-01  5.01749476e+00]
  [ 7.88404618e-02 -9.94454583e-01 -6.96007405e-02 -1.03080299e+00]
  [ 5.38703626e-01  1.01246432e-01 -8.36389600e-01  1.07954058e+00]]

 [[ 8.97537189e-01  2.04987985e-02  4.40462022e-01  4.25286147e+00]
  [ 6.49453298e-02 -9.94169840e-01 -8.60722597e-02 -1.12924661e+00]
  [ 4.36129680e-01  1.05859005e-01 -8.93635705e-01  5.03125661e-01]]

 [[ 9.46216725e-01  1.43974982e-02  3.23212966e-01  3.29551469e+00]
  [ 4.33182496e-02 -9.95652127e-01 -8.24643667e-02 -1.24790673e+00]
  [ 3.20620396e-01  9.20301829e-02 -9.42726369e-01 -3.68651864e-01]]

 [[ 9.81293518e-01  4.25306163e-03  1.92470628e-01  2.22828057e+00]
  [ 1.87668072e-02 -9.97107742e-01 -7.36475258e-02 -1.26835532e+00]
  [ 1.91600726e-01  7.58818988e-02 -9.78535180e-01 -3.80212220e-01]]

 [[ 9.95584044e-01  7.45365522e-03  9.35780613e-02  1.12308973e+00]
  [ 1.48354975e-02 -9.96808567e-01 -7.84384406e-02 -1.29550509e+00]
  [ 9.26947601e-02  7.94803370e-02 -9.92517283e-01 -2.92097158e-01]]

 [[ 9.85964928e-01  7.98170831e-03 -1.66761663e-01 -1.04431209e+00]
  [-5.27115149e-03 -9.96870306e-01 -7.88784322e-02 -1.35590162e+00]
  [-1.66869335e-01  7.86503937e-02 -9.82837088e-01 -1.70314955e-01]]

 [[ 9.56248184e-01  3.42653729e-03 -2.92536611e-01 -2.12674568e+00]
  [-2.46620946e-02 -9.95428058e-01 -9.22754744e-02 -1.37339932e+00]
  [-2.91515335e-01  9.54528204e-02 -9.51791767e-01 -1.15686476e-01]]

 [[ 9.17761775e-01  2.05967036e-02 -3.96596898e-01 -3.21393790e+00]
  [-2.07386984e-02 -9.94805894e-01 -9.96551081e-02 -1.40894450e+00]
  [-3.96589498e-01  9.96845524e-02 -9.12567674e-01 -7.42257468e-02]]

 [[ 8.53935430e-01  3.11967919e-03 -5.20369628e-01 -4.02908419e+00]
  [-5.15786447e-02 -9.94550441e-01 -9.06038860e-02 -1.29596338e+00]
  [-5.17816497e-01  1.04209828e-01 -8.49120949e-01  8.98934516e-01]]

 [[ 7.79048619e-01  8.41124969e-03 -6.26907091e-01 -4.73572386e+00]
  [-6.47711149e-02 -9.93480025e-01 -9.38197335e-02 -1.26018737e+00]
  [-6.23608813e-01  1.13695605e-01 -7.73424435e-01  1.59748990e+00]]

 [[ 9.84967791e-01 -1.83604765e-03  1.72728341e-01  5.71785986e+00]
  [-1.00892319e-02 -9.98847908e-01  4.69154979e-02  1.59323596e+00]
  [ 1.72443203e-01 -4.79529506e-02 -9.83851542e-01  3.67999406e-01]]

 [[ 9.96836585e-01 -5.12728993e-02  6.07281880e-02  4.73497199e+00]
  [-4.92048563e-02 -9.98172664e-01 -3.50744133e-02  1.57486624e+00]
  [ 6.24155841e-02  3.19753366e-02 -9.97537905e-01  1.82806881e-01]]

 [[ 9.64466184e-01 -4.00341829e-02  2.61155594e-01  2.83492625e+00]
  [-2.62664603e-02 -9.98085267e-01 -5.59988595e-02  1.49509264e+00]
  [ 2.62897420e-01  4.71493733e-02 -9.63671045e-01 -5.94798933e-01]]

 [[ 9.87274722e-01 -2.32381938e-02  1.57316907e-01  1.55518735e+00]
  [-2.18668768e-02 -9.99706356e-01 -1.04423314e-02  1.45351116e+00]
  [ 1.57513373e-01  6.86942041e-03 -9.87492961e-01 -5.78267434e-01]]

 [[ 9.99998294e-01  1.05677599e-06 -1.84726312e-03  4.67780515e-01]
  [ 3.28095395e-06 -9.99999275e-01  1.20403699e-03  1.44002888e+00]
  [-1.84726051e-03 -1.20404099e-03 -9.99997569e-01 -5.28641265e-01]]

 [[ 9.94929901e-01  5.77334334e-03 -1.00404984e-01 -6.58855655e-01]
  [ 1.44479014e-03 -9.99068410e-01 -4.31303293e-02  1.40248024e+00]
  [-1.00560454e-01  4.27665901e-02 -9.94011375e-01 -4.87051259e-01]]

 [[ 9.66380706e-01 -5.49411865e-02 -2.51176825e-01 -1.79567597e+00]
  [-5.90161145e-02 -9.98218998e-01 -8.71377480e-03  1.37530445e+00]
  [-2.50250733e-01  2.32443041e-02 -9.67901995e-01 -4.41455875e-01]]

 [[ 9.34074547e-01 -5.29147971e-02 -3.53135619e-01 -2.92059040e+00]
  [-6.47847493e-02 -9.97659596e-01 -2.18693039e-02  1.33435980e+00]
  [-3.51151929e-01  4.33053627e-02 -9.35316507e-01 -4.04465710e-01]]

 [[ 9.56364324e-01 -5.03161586e-02 -2.87811681e-01 -4.75226752e+00]
  [-2.42860884e-02 -9.95340966e-01  9.33088795e-02  1.35802571e+00]
  [-2.91165701e-01 -8.22474635e-02 -9.53130573e-01  5.78434824e-01]]

 [[ 9.02879646e-01 -1.24350461e-01 -4.11515865e-01 -5.70130022e+00]
  [-6.06527259e-02 -9.84522953e-01  1.64425670e-01  1.35362360e+00]
  [-4.25593223e-01 -1.23497032e-01 -8.96447930e-01  9.47080318e-01]]]
ERROR: database path dosen't exist -- please check database.db.

**Comment by hhxphh** [comment]
i change a computer ,and it works...... so weried
